### ISSUE TITLE
Eclipse crashes after editor changes 

### ISSUE THREAD

**Issue by urbandroid** [eclipse-platform/eclipse.platform.swt#1241] opened 2024-05-20 16:59 UTC
Open multiple projects on eclipse
Open editor on any class file and try to make some changes.
It crashes.

Version: 2023-12 (4.30.0)
Build id: 20231201-2043

Enviroment:
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)

[hs_err_pid95172.log](https://github.com/eclipse-platform/.github/files/15379887/hs_err_pid95172.log)
[hs_err_pid99410.log](https://github.com/eclipse-platform/.github/files/15381895/hs_err_pid99410.log)
[hs_err_pid114220.log](https://github.com/eclipse-platform/.github/files/15381896/hs_err_pid114220.log)
[hs_err_pid115074.log](https://github.com/eclipse-platform/.github/files/15381897/hs_err_pid115074.log)
Log file at the attachment

**Comment by jukzi** [comment] 2024-05-21 06:56
Probably a duplicate of other LInux/GTK crashes with SWT please see the other bug issues, some even show workarounds.

**Comment by iloveeclipse** [comment] 2024-05-21 06:57
```
#  SIGSEGV (0xb) at pc=0x00007fad5aed01f8, pid=115074, tid=115075
#
# JRE version: OpenJDK Runtime Environment Temurin-21.0.2+13 (21.0.2+13) (build 21.0.2+13-LTS)
# Java VM: OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (21.0.2+13-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libwebkit2gtk-4.0.so.37+0xdb61f8]
```

Webkit again.

**Comment by iloveeclipse** [comment] 2024-05-21 06:59
Closing as duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/843

**Closed** 2024-05-21 07:58 UTC
Labels: bug, Linux/GTK, Webkit
