### ISSUE TITLE
Bug in using Eclipse for C/C++ developers

### ISSUE THREAD

**Issue by BenBorre** [eclipse-platform/eclipse.platform.swt#439] opened 2022-10-19 10:19 UTC
This is the only one Eclipse environment I have installed on my PC (nothing like Java, etc...).
I installed it and removed it (roughly by deleting .eclipse and .p2 folders). Sometimes Project Properties,(then I had access to DTC ...), sometimes not. When using the right DTC, it pointed out to a problem of missing make - the famous make.exe (or at the time nmake) I used long time ago. Hard to find it.
Never been able to make Project Properties available again, after multiple deletes and re-installs. So I decided to go (after a donation) for getting environment variables out of the way, one by one.

When I go to Tutorials->C/C++ Development and C++ projects I get an <html>
<head>
	
	<title></title>
	<meta name="generator" content="LibreOffice 7.4.1.2 (Windows)"/>
	<style type="text/css">
		@page { size: 21cm 29.7cm; margin: 2cm }
		p { line-height: 115%; margin-bottom: 0.25cm; background: transparent }
		a:link { color: #000080; so-language: zxx; text-decoration: underline }
	</style>
</head>
<body lang="fr-BE" link="#000080" vlink="#800000" dir="ltr">

org.apache.jasper.JasperException: 			PWC6033: Error in Javac compilation for JSP PWC6197: An error 			occurred at line: 41 in the jsp file: /index.jsp PWC6199: 			Generated servlet error: System cannot be resolved
--

</body>
</html> 
error.
I see this is probably due missing environment variable definitions (which I can't access).

See full report in attachment.

Many thanks for an old developer coming in again after several years of working in other topics.
[Error Log.pdf](https://github.com/eclipse-platform/eclipse.platform.swt/files/9819504/Error.Log.pdf)

**Comment by merks** [comment] 2022-10-19 13:46
@jonahgraham I can only reproduce this with CDT, not the other packages...

**Comment by iloveeclipse** [comment] 2022-10-19 13:52
>  I can only reproduce this with CDT, not the other packages...

It is a duplicate of https://github.com/eclipse-platform/eclipse.platform.ua/issues/18

**Closed by iloveeclipse** 2022-10-19 13:52 UTC
