### ISSUE TITLE
Find/Replace dialog position scrolling on Wayland

### ISSUE THREAD

**Issue by psybases** [eclipse-platform/eclipse.platform.swt#1597] opened 2024-11-18 07:54 UTC
On Fedora 40 running 
Eclipse Version: 2024-09 (4.33.0) Build id: 20240905-0614 
on KDE under Wayland
but also 
on  Ubuntu 24.04.1 LTS using Gnome under Wayland
with
Eclipse Platform	4.33.0.v20240903-0618	
Standard Widget Toolkit	3.127.0.v20240903-0618

when I open the Find/Replace dialog (Ctrl-F) (and I have already opened a file) and move the mouse or type anything
in the dialog, the widgets inside the dialog will start moving/scrolling.
This will result in all the widgets inside this dialog to move right and down until they disappear.
See the attachment.
![Screenshot_20241001_101648](https://github.com/user-attachments/assets/5128c276-c5ef-4644-a96f-94cfc514c503)

**Comment by HeikoKlare** [comment] 2024-11-18 08:19
This is a duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/1447

The issue will be resolved in the 2024-12 release. For the 2024-09 release, the only workaround is to temporarily switch back to the existing find/replace dialog. For information how to do so, see [the news](https://eclipse.dev/eclipse/news/4.33/platform.php#find-replace-overlay).

**Closed by HeikoKlare** 2024-11-18 08:19 UTC
