### ISSUE TITLE
StyledText: massive performance problem drawing lines with "box" characters < 0x20

### ISSUE THREAD

**Issue by tmssngr** [eclipse-platform/eclipse.platform.swt#1423] opened 2024-08-27 09:23 UTC
**Describe the bug**
If a file contains a larger number of characters that are not supported by the font, scrolling becomes terrible slow.

**To Reproduce**
- unpack the attached zip file
- run following snippet:
```java
import java.io.*;
import java.nio.file.*;

import org.eclipse.swt.*;
import org.eclipse.swt.custom.*;
import org.eclipse.swt.layout.*;
import org.eclipse.swt.widgets.*;

public class StyledTextPerformanceProblem {

	public static void main(String[] args) throws IOException {
		final StringBuilder buffer = new StringBuilder();
		try (BufferedReader reader = Files.newBufferedReader(Path.of("test.txt"))) {
			String line;
			while ((line = reader.readLine()) != null) {
				buffer.append(line);
				buffer.append("\n");
			}
		}

		final Display display = new Display();

		final Shell shell = new Shell(display);
		shell.setLayout(new FillLayout());

		final StyledText styledText = new StyledText(shell, SWT.V_SCROLL | SWT.H_SCROLL);
		styledText.setText(buffer.toString());

		shell.setSize(1000, 800);
		shell.open();
		while (!shell.isDisposed()) {
			if (!display.readAndDispatch()) {
				display.sleep();
			}
		}
		display.dispose();
	}
}
```
- scroll down until the long lines occur

**Expected behavior**
That the performs is the same as for "normal" characters.

**Screenshots**

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
Tried on Windows 11.

**Workaround (or) Additional context**
No known workaround.
[test.txt.zip](https://github.com/user-attachments/files/16759745/test.txt.zip)

**Comment by laeubi** [comment] 2024-08-27 13:57
@KorkyPlunger in this case you might want to debug / improve and provide a PR to fix this?

**Comment by jukzi** [comment] 2024-08-27 14:43
is this a duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/414 ?

**Comment by jukzi** [comment] 2024-08-27 16:30
closing as duplicate

**Closed by jukzi** 2024-08-27 16:30 UTC
Labels: performance
