### ISSUE TITLE
[Wayland] Clipboard (used by StyledText) doesn't copy to external applications (eg GEdit)

### ISSUE THREAD

**Issue by ichbindannmalwegmann** [eclipse-platform/eclipse.platform.swt#479] opened 2022-11-30 14:15 UTC
# Affected version

Eclipse: 2022-09
Gnome: 43.1
OS: Fedora 37

# Bug summary
Cannot copy text from Eclipse to GEdit / GNOME Text Editor / GNOME Terminal. The opposite direction works. Also pasting into LibreOffice Writer works.

# Steps to reproduce
1. Copy text in Eclipse.
2. Paste text in GEdit.

# What happened
Nothing (no text).

# What did you expect to happen
The copied text should be pasted.

# Notes

If I use "wl-paste -t STRING" I can paste a text to the command line. Without the "-t" option, it doesn't work.

I pasted the bug here "https://gitlab.gnome.org/GNOME/mutter/-/issues/2536" and the answer was:

Assuming Eclipse runs as a Wayland client, it should not use X11-style atom names like "STRING" or "UTF8_STRING" for text content, but proper mimetypes like text/plain or text/plain;charset=utf8. This is something that should be fixed in Eclipse, only mimetype strings conform to the Wayland protocol.

**Comment by mickaelistria** [comment] 2022-12-01 15:32
It looks like since my last OS update a few hours, I also lost the capability to copy from Eclipse IDE to paste into Firefox. That is extremely annoying!

**Comment by mickaelistria** [comment] 2022-12-02 10:46
This happens only with StyledText and can be reproduced with older versions of SWT.
This is not per-se a regression in SWT; it's more that StyledText way of copying used to work fine but is now invalid with more recent Wayland. StyledText still needs a fix to use the necessary way of copying.

**Comment by mickaelistria** [comment] 2022-12-02 11:31
The issue is not in StyledText but in Clipboard. If you run the ClipboardExample, then you can reproduce the issue by hitting the "Copy" action that delegates to Clipboard.

**Comment by mickaelistria** [comment] 2022-12-02 11:59
One workaround is to copy from Eclipse, paste into a X11 application such as Slack, then to select all and copy again from that application and finally you can paste in plain Wayland apps ;)

**Comment by majanojoel** [comment] 2022-12-03 01:50
This seems to be a duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/421

**Comment by mickaelistria** [comment] 2022-12-14 16:22
Closing as duplicate of #421

**Closed by mickaelistria** 2022-12-14 16:22 UTC
Labels: Wayland
