### ISSUE TITLE
 Eclipse is called "NewApplication" in macOS menu bar

### ISSUE THREAD

**Issue by vadym-yusanenko** [eclipse-platform/eclipse.platform.swt#831] opened 2023-10-06 18:20 UTC
**Describe the bug**
Eclipse is called "NewApplication" in macOS menu bar instead of "Eclipse".

**To Reproduce**
Open Eclipse and pay attention to top left corner of macOS menu bar.

**Expected behavior**
"Eclipse" is shown instead of "NewApplication" in menu bar.

**Screenshots**
<img width="546" alt="Screenshot 2023-10-06 at 20 53 46" src="https://github.com/eclipse-platform/eclipse.platform.swt/assets/748882/3db24b27-6e2c-4bc1-bf84-e4cbdb0f2be0">

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [ ] Linux
- - [x] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
OS: macOS Sonoma 14.0 (23A344)

3. JRE/JDK version
org.eclipse.justj.openjdk.hotspot.jre.full.macosx.aarch64_20.0.2.v20230801-2057
 
**Version since**
 2023-09 (4.29)

**Workaround (or) Additional context**
No known workarounds, although on rare occassions this bug disappears all of a sudden but appears right after again.

**Comment by Phillipus** [comment] 2023-10-06 18:41
This is a duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/779 and has been fixed.

**Comment by Phillipus** [comment] 2023-10-06 18:44
I'll close this one, then.

**Closed by Phillipus** 2023-10-06 18:44 UTC
