### ISSUE TITLE
Keyboard shortcuts for radio buttons don't work anymore

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.swt#6] opened 2022-03-29 08:19 UTC
Moving the bug from bugzilla [Bug 579460](https://bugs.eclipse.org/bugs/show_bug.cgi?id=579460) - Keyboard shortcuts for radio buttons don't work anymore

I discovered in 2 dialogs, that the following shortcut keys for the radio buttons do not work anymore since Eclipse 4.23

![radio-i-Accept](https://user-images.githubusercontent.com/77106773/160566049-9a743e14-2e35-4d75-a0c0-0b95982db152.png)
\<Alt>-A in the review licenses dialog
![radio-Keep-field-reference](https://user-images.githubusercontent.com/77106773/160566279-858d5fbc-4d54-4cf4-97da-c6758d18fc72.png)
\<Alt>-K in the encapsulate field dialog

**Comment by sravanlakkimsetti** [comment] 2022-03-29 08:21
From Rolf
This is a regression from [Bug 578103](https://bugs.eclipse.org/bugs/show_bug.cgi?id=578103)

In mnemonicHit there is a workaround for a similar issue as in [Bug 578103](https://bugs.eclipse.org/bugs/show_bug.cgi?id=578103). I think that removing this check, and always do the click will fix the this issue.

**Comment by wolfgang-ch** [comment] 2022-04-03 08:31
This bug is very annoying when you are using shortcuts very often and this workflow is now "broken".

Like the `Inline Method` dialog, you open it with `<Alt><Shift> I`, press `A`, `<Enter>` and all would be now inlined.

![image](https://user-images.githubusercontent.com/1283445/161418634-15f9af6b-3fe2-4a4c-a505-1104f35e2b3b.png)

**Comment by niraj-modi** [comment] 2022-04-04 03:16
@rolfth 
Please investigate this. Thanks!

**Comment by wolfgang-ch** [comment] 2022-04-04 05:13
This bug occurs not only in the Eclipse IDE it also pertains all RCP apps which are created with this Eclipse version.

**Comment by mickaelistria** [comment] 2022-04-04 08:02
Wouldn't it be worth reverting patch for https://bugs.eclipse.org/bugs/show_bug.cgi?id=578103 if it does cause such a regression?

**Comment by iloveeclipse** [comment] 2022-04-05 07:47
Another report for same problem: https://bugs.eclipse.org/bugs/show_bug.cgi?id=579573

Looking on the bug that was actually fixed (https://bugs.eclipse.org/bugs/show_bug.cgi?id=578103) I assume we should consider revert, because the regression is more severe as the original one.

@rolfth : can you please provide a fix or revert of the original patch?

**Comment by niraj-modi** [comment] 2022-04-06 09:03
> I will try to look in to it tonight.

Thanks Rolf for the fix, closing for 4.24 M1

**Closed by niraj-modi** 2022-04-06 09:03 UTC
Labels: bug

**Comment by niraj-modi** [comment] 2022-04-07 11:04
Verified the fix on Win10 using Eclipse Build id: I20220407-0240.

Had a quick discussion with @sravanlakkimsetti  planning to back-port this to 4.23+ shortly.

**Comment by rolfth** [comment] 2022-04-07 12:24
Note that the included test case does not work on Linux, see https://github.com/eclipse-platform/eclipse.platform.swt/issues/27
