### ISSUE TITLE
Regression in Tree from Bug 575787

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-platform/eclipse.platform.swt#287] opened 2022-08-04 20:35 UTC
[Bug 575787](https://bugs.eclipse.org/bugs/show_bug.cgi?id=575787) which optimized `Tree.setItemCount` causes `Tree.indexOf(TreeItem)` to return negative numbers.

This issue was originally reported as a bug with CDT in [Bug 580518](https://bugs.eclipse.org/bugs/show_bug.cgi?id=580518)

**To Reproduce**

At the moment the steps to reproduce involve using CDT on Windows:

1. Install CDT 10.7 in Platform 4.24, gcc+gdb will be needed too
2. Create two Hello World projects
3. In project A insert 5 breakpoints
4. In project B insert 2 breakpoints
5. Debug project B
6. In the Breakpoints view toggle "Show Breakpoints Supported by Selected Target"

I'll try to find time to make a standalone test case. The above test case uses virtual trees + platform debug's async view model which makes it fairly complicated.

**Expected behavior**

When toggle is on, only 2 breakpoints of project B displayed. When toggle is off, all 7 breakpoints displayed.

**Actual behaviour**

When toggled back off, the breakpoints view is "corrupted" - see screenshot. There is also an exception in the CDT code due to the index not being in the expected range of >= -1. See [bug 580518](https://bugs.eclipse.org/bugs/show_bug.cgi?id=580518#c2) for full stack trace.

**Screenshots**

![image](https://user-images.githubusercontent.com/679236/182942391-022cf90b-9ba9-4352-9a37-8e5417fae369.png)

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

Definitely Windows, can't seem to reproduce on Linux.

7. Additional OS info (e.g. OS version, Linux Desktop, etc)

8. JRE/JDK version

JustJ Java 17 as shipped with EPP.
 
**Version since**

Since commit 17b4024759c8084afa680a06b7b2803463e84114 - reverting 17b4024759c8084afa680a06b7b2803463e84114 resolves the issue.

**Comment by jonahgraham** [comment] 2022-08-04 20:44
Instead of the steps in my original I can reproduce with Java + some other debug environment. By creating 5ish Java breakpoints and 5ish non-Java breakpoints and then toggling "Show Breakpoints Supported by Selected Target" while debugging the Java project will lead to the same problem, with the following exception:

```
java.lang.ArrayIndexOutOfBoundsException: arraycopy: source index -1 out of bounds for object array[8]
	at java.base/java.lang.System.arraycopy(Native Method)
	at org.eclipse.debug.internal.ui.model.elements.ElementContentProvider.getElements(ElementContentProvider.java:197)
	at org.eclipse.debug.internal.ui.model.elements.BreakpointManagerContentProvider.getChildren(BreakpointManagerContentProvider.java:994)
	at org.eclipse.debug.internal.ui.model.elements.ElementContentProvider.retrieveChildren(ElementContentProvider.java:99)
	at org.eclipse.debug.internal.ui.model.elements.ElementContentProvider$1.run(ElementContentProvider.java:58)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

and screenshot:

![image](https://user-images.githubusercontent.com/679236/182948788-dae50497-2918-4b98-b522-dcc18bc8f00a.png)

**Comment by jonahgraham** [comment] 2022-08-05 00:45
> Instead of the steps in my original [...]

Explicit steps that don't need as much setup to experiment with:

1. With [eclipse-SDK-I20220804-1800-win32-x86_64](https://download.eclipse.org/eclipse/downloads/drops4/I20220804-1800/download.php?dropFile=eclipse-SDK-I20220804-1800-win32-x86_64.zip) install `org.eclipse.lsp4e` and `org.eclipse.lsp4e.debug`
2. Create a Java project
3. Create a Java class with a `main`, and enough lines of code to insert 5 breakpoints
4. Create another file (e.g. `hello.js`), open in Generic Editor and add enough lines of code to insert 5 breakpoints
5. Debug `main`
6. In Breakpoints view turn on and then off  "Show Breakpoints Supported by Selected Target"
7. The Breakpoints view will now be corrupted:

![image](https://user-images.githubusercontent.com/679236/182978361-870cb96e-5068-44ab-9af5-9bb2836f7641.png)

**Comment by niraj-modi** [comment] 2022-08-05 08:28
@SyntevoAlex Please have a look.

**Comment by SyntevoAlex** [comment] 2022-08-05 11:57
Will do, but it will probably have to wait a few days.

**Comment by Phillipus** [comment] 2022-08-05 14:01
> Definitely Windows, can't seem to reproduce on Linux.

I was going to test on Mac but couldn't get past:

>  install org.eclipse.lsp4e and org.eclipse.lsp4e.debug

I tried adding the update site  at `https://download.eclipse.org/lsp4e/releases/latest/` to Eclipse but get "There are no items available"

**Comment by merks** [comment] 2022-08-05 14:20
It's in every release train repository:

https://download.eclipse.org/releases/2022-06
https://download.eclipse.org/releases/2022-09

**Comment by Phillipus** [comment] 2022-08-05 14:28
> It's in every release train repository:

It's certainly there in the repo, but when I try to install from within Eclipse ("Help -> Install New Software") I can only see `LSP4J SDK` in the list of available software. Unless it's part of another package?

**Comment by jonahgraham** [comment] 2022-08-05 15:05
@Phillipus Perhaps you typed lsp4*j* instead of lsp4*e*? Anyway the mapping from ID to name is not always obvious/known - so here is more step-by-step:

> 1. [...] install `org.eclipse.lsp4e` and `org.eclipse.lsp4e.debug`

In the install new software it is called "Language Server Protocol client for Eclipse IDE (incubation)" and "Debug Adapter Client for Eclipse IDE (incubation)"*:

![image](https://user-images.githubusercontent.com/679236/183104593-6549b822-4934-4150-bc59-ac828e542789.png)

Though you may prefer to do it explicitly at the command line with `./eclipse/eclipse -data data -consoleLog -nosplash  -application org.eclipse.equinox.p2.director -repository https://download.eclipse.org/releases/2022-09 -installIU org.eclipse.lsp4e -installIU org.eclipse.lsp4e.debug`

\* Perhaps a feature request for "Install New Software" is to know/understand plug-in IDs as typing "org.eclipse.lsp4e" does not give useful results for installing LSP4E

**Comment by merks** [comment] 2022-08-05 15:06
I think this feature includes both those bundles and yes you generally can't choose to install bundles but only features.:

https://download.eclipse.org/oomph/archive/reports/download.eclipse.org/staging/2022-09/index/org.eclipse.lsp4j.sdk.feature.group_0.14.0.v20220526-1520.html#org.eclipse.equinox.p2.iu;_org.eclipse.lsp4j.debug_[0.14.0.v20220526-1518,0.14.0.v20220526-1518]

**Comment by jonahgraham** [comment] 2022-08-05 15:09
> I think this feature [...]

@merks comment refers to lsp4**j** - you need lsp4**e**

FWIW The lsp4e bundles are in p2 and can be installed in the gui or command line even though they are not features.

**Comment by Phillipus** [comment] 2022-08-05 15:23
@jonahgraham Thanks for the more detailed explanation.

I installed those plugins and am now able to set breakpoints on JS files as well as Java files and these are showing in the Breakpoints view. However, pressing "Show Breakpoints Supported by Selected Target" on and off does nothing. (Testing on Windows before I test on Mac.)

**Comment by jonahgraham** [comment] 2022-08-05 15:28
> I installed those plugins and am now able to set breakpoints on JS files as well as Java files and these are showing in the Breakpoints view. However, pressing "Show Breakpoints Supported by Selected Target" on and off does nothing. (Testing on Windows before I test on Mac.)

Did you debug `main`? Are you stopped at a Java breakpoint:

> 5. Debug `main`

> ![image](https://user-images.githubusercontent.com/679236/182978361-870cb96e-5068-44ab-9af5-9bb2836f7641.png)

**Comment by Phillipus** [comment] 2022-08-05 15:40
> Did you debug main? Are you stopped at a Java breakpoint:

OK, thanks for that. Got it working now.

So I can reproduce this on Windows but not Mac. 👍 So, as you say, a Windows issue.

**Comment by SyntevoAlex** [comment] 2022-08-08 02:36
Thanks, I was able to reproduce using your steps. I'm working on a patch.

**Comment by iloveeclipse** [comment] 2022-08-15 15:32
> Thanks, I was able to reproduce using your steps. I'm working on a patch

@SyntevoAlex : do you think you will make it for 4.25 M3? M3 is planned to be this week.

**Comment by SyntevoAlex** [comment] 2022-08-15 15:37
I'm not completely sure. A few other tasks required my attention.

I already fixed one problem in the patch, but there is another problem. Seems to be a regression from sole other recent patch. I need to investigate it.

**Comment by iloveeclipse** [comment] 2022-08-15 16:19
@SyntevoAlex : would it be OK to drop optimization then, since this causes a regression?

@jonahgraham : how severe the problem is? Should we revert 17b4024759c8084afa680a06b7b2803463e84114 for 4.25 M3?

**Comment by SyntevoAlex** [comment] 2022-08-15 16:35
I understand that it's been 8 months since the patch was merged and the problem is only noticed now. Sounds like it's not too much of a nuisance.

**Comment by jonahgraham** [comment] 2022-08-15 19:21
For the problematic use case in CDT it is  bad as breakpoints view is busted and requires restarting IDE. However I don't know how many people use that feature vs benefit from optimization. I would lean on leaving it broken in 4.25 over removing the optimization as my understanding is reverting optimization would essentially be a big performance regression?

Is there a mitigation we can do in 4.25? Eg can breakpoints view behave differently?

**Comment by iloveeclipse** [comment] 2022-08-15 19:30
> my understanding is reverting optimization would essentially be a big performance regression?

Not really.  The Windows port worked "good enough" for years without this optimization.
Broken Breakpoints view and hanging UI is a severe recent regression.

> However I don't know how many people use that feature

We also don't know how many people are affected by other things that do not work anymore,  simply because they don't know where the problem is coming from. 

Waiting 3 months longer for optimization (for performance issue that was there for years) is better as delivering second broken platform release.

@SyntevoAlex : could you please provide a clean revert of the code in question for M3?

**Comment by SyntevoAlex** [comment] 2022-08-15 22:20
I will try to fix tomorrow, and if it doesn't work, I'll compose a revert.

**Comment by SyntevoAlex** [comment] 2022-08-16 23:40
Please find patch in #318

**Comment by iloveeclipse** [comment] 2022-08-24 11:30
Schould be fixed via https://github.com/eclipse-platform/eclipse.platform.swt/pull/318

**Closed by iloveeclipse** 2022-08-24 11:30 UTC
Labels: regression, Windows
