### ISSUE TITLE
UnsatisfiedLinkError of swt-win32-4965r8.dll on Windows Server 2008 R2

### ISSUE THREAD

**Issue by serjiokov** [eclipse-platform/eclipse.platform.swt#1252] opened 2024-05-23 14:26 UTC
Hello,

Issue description: 

Recently we switched to the  latest Eclipse SDK release 
https://download.eclipse.org/releases/2024-06  version build [202405031000](https://download.eclipse.org/releases/2024-06/202405031000) 
and bumped with product crash on specific OS's:  Windows 8 / Windows Server 2008 
due to **UnsatisfiedLinkError of swt-win32-4965r8.dll**

PS:
Let us please, know if you reduce support of OS like Windows 8 / Windows 2008 RC  

The original issue in DBeaver product:
https://github.com/dbeaver/dbeaver/issues/34034

**Comment by HeikoKlare** [comment] 2024-05-23 14:45
Could you please detail from which Eclipse version you switched to the new one?

I am not aware of very recent changes that (explicitly) reduced support for older Windows version. But note that, if I am not mistaken, the Windows versions you mention are out of support for quite some time, so
1. probably no one (explicitly) considers compatibility with such versions when making changes to SWT, and
2. functionality specific for these old version has already been reduced over the last years with changes like in https://github.com/eclipse-platform/eclipse.platform.swt/pull/370, precisely https://github.com/eclipse-platform/eclipse.platform.swt/pull/370/commits/3cc6898797a4ee0cfebc515482fbb165643d261a

**Comment by serjiokov** [comment] 2024-05-23 14:49
Thanks for your response.

**Comment by serjiokov** [comment] 2024-06-06 09:21
Hello, 
we switched from 
<eclipse-version>2024-06/202404121000/</eclipse-version>
to
<eclipse-version>2024-06/**202405031000**/</eclipse-version>

The entire support of Windows 7, Windows 8, Windows Server 2008 R2, MacOS Catalina 10.15.7
is broken due to   
```
Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	D:\bin\dbeaver\home\swt-win32-4965r8.dll: Belirtilen yordam bulunamadı
	no swt-win32 in java.library.path:
```
References issues 
https://github.com/dbeaver/dbeaver/issues/34244
https://github.com/dbeaver/dbeaver/issues/34197
https://github.com/dbeaver/dbeaver/issues/34034
https://github.com/dbeaver/dbeaver/issues/30700

Could you please confirm that  `Windows 7, Windows 8, Windows Server 2008 R2, MacOS Catalina 10.15.7`
out of support?

**Comment by HeikoKlare** [comment] 2024-06-06 09:35
I am not aware of any changes in that date range that have actively removed support for those operating systems. We had additions in the Windows native bindings (https://github.com/eclipse-platform/eclipse.platform.swt/commit/94d9c5b2db2ab85c8ca4001f124d354f36ab591d), which might be a reason for outdated Windows versions not to work (properly) anymore, as these Windows version may not provide the accessed methods. But I am not sure whether that's really the root cause here as, first, I think there are also other OS methods not provided by older Windows versions which do not make the SWT DLLs loading fail and, second, I do not see changes to MacOS in SWT, but you say that MacOS is also not working anymore.

In https://github.com/dbeaver/dbeaver/issues/34244#issuecomment-2146796800, this error message is posted, which actually sounds like missing methods provided by the OS:
```
java.lang.UnsatisfiedLinkError: Could not load SWT library. 
Reasons: 
	C:\Users\***\AppData\Local\DBeaver\swt-win32-4965r8.dll: The specified procedure could not be found
	no swt-win32 in java.library.path: 
```
But this does still not explain problems with MacOS.

**Comment by serjiokov** [comment] 2024-06-06 10:16
The users who are using Oses below ( Windows 7, 8, 2008 ) will bumped with the same set issue `UnsatisfiedLinkError` after switching to Eclipse release 2024-06, it not to be so friendly for them. Could you please investigate it?

**Comment by HeikoKlare** [comment] 2024-06-06 10:28
I understand that this is annoying and of course it would be great to have some tracking of minimal system requirements and some validation on startup and update whether they are fulfilled. We had a similar discussion in https://github.com/eclipse-platform/.github/issues/193.

> Could you please investigate it?

The problem is: Who do you mean by "you"? Eclipse is a [community project](https://github.com/eclipse-platform#community), so it up to its users to implement fixes and required features.  I (personally) cannot do that, since this is not an issue for me and my company, as users of our products do not use outdated Windows versions. And independent from what my company needs directly, I am sorry to say that there are far more important things for the Eclipse platform to be done than supporting outdated operating systems or handling that someone uses them. Note that this is not about dropping support for like a two-year-old OS, but for OS versions have been out-of-support for some time anyway. If it is important for you to have that feature, it would be great if you could contribute that to the Eclipse platform.

**Comment by greenozon** [comment] 2024-06-13 14:13
this is critical issue, hit it as well recently, please do not drop support of big list of Windows OSes like 7, etc

details:

```
	C:\Users\User\.swt\lib\win32\x86_64\swt-win32-4965r11.dll: The specified procedure could not be found
	Can't load library: C:\Users\User\.swt\lib\win32\x86_64\swt-win32.dll
	Can't load library: C:\Users\User\.swt\lib\win32\x86_64\swt.dll
	C:\Users\User\.swt\lib\win32\x86_64\swt-win32-4965r11.dll: The specified procedure could not be found

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:345)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:254)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.internal.win32.STARTUPINFO.<clinit>(STARTUPINFO.java:42)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:149)
	at com.pnfsoftware.jeb.rcpclient.extensions.app.App.onPreDisplayCreation(App.java:93)
	at com.pnfsoftware.jeb.rcpclient.JebApp.onPreDisplayCreation(JebApp.java:52)
	at com.pnfsoftware.jeb.rcpclient.extensions.app.App.<init>(App.java:70)
	at com.pnfsoftware.jeb.rcpclient.JebApp.<init>(JebApp.java:37)
	at com.pnfsoftware.jeb.rcpclient.Launcher.main(Launcher.java:18)

```

**Comment by Phillipus** [comment] 2024-06-14 15:28
> I am not aware of any changes in that date range that have actively removed support for those operating systems. We had additions in the Windows native bindings (https://github.com/eclipse-platform/eclipse.platform.swt/commit/94d9c5b2db2ab85c8ca4001f124d354f36ab591d), which might be a reason for outdated Windows versions not to work (properly) anymore, as these Windows version may not provide the accessed methods.

Could be. That commit references `SystemParametersInfoForDpi` See https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-systemparametersinfofordpi:

```
Minimum supported client 	Windows 10, version 1607 [desktop apps only]
Minimum supported server 	Windows Server 2016 [desktop apps only]
```

> But this does still not explain problems with MacOS.

That'll be https://github.com/eclipse-equinox/equinox/commit/69b907ead3134f0d42deef6c1b686b9af03ec428

But these are outdated OS's and in order to progress Eclipse has to move on. And, in fact, these minimum versions are already documented. See https://eclipse.dev/eclipse/development/plans/eclipse_project_plan_4_32.xml#target_environments where it states:

> Eclipse 4.32 is tested and validated on the following reference platforms (this list is updated over the course of the release cycle):
> | Operating System | Version | Hardware |
> |--------|--------|--------|
> | Windows | 10<br>11 | x86 64-bit |
> | Apple macOS | 12<br>13  | x86 64-bit |

**Comment by Phillipus** [comment] 2024-06-17 14:25
> I am not aware of any changes in that date range that have actively removed support for those operating systems.

My curiosity was such that I installed Windows 8 in a VM and bisected where things stopped working. Specifically, it was the new `v4965r7` binaries at commit 3d87b2212403cfe7ffd3dccb25fe6195d6566df2. This is where the new Windows OS native calls manifest that were committed in 94d9c5b2db2ab85c8ca4001f124d354f36ab591d and f80937230f0caf83f0c38fd6536654b301b8934d. But, as I said above, I doubt this will be reverted.

**Closed** 2024-06-17 21:11 UTC
Labels: Windows

**Comment by laeubi** [comment] 2024-06-18 03:48
One problem is of course test-hardware, we don't have win7 / 8 hardware to test as far as I know (at least not github), otherwise one might think about having an if/then else at the respective code.

**Comment by HeikoKlare** [comment] 2024-06-26 08:03
> this is critical issue, hit it as well recently, please do not drop support of big list of Windows OSes like 7, etc

I tried to give constructive input for this topic, so it would be great to keep the discussion constructive and avoid such over-dramatic statements and giving negative votes on my constructive explanations of the situation. _No one_ has dropped support for a "big list of Windows OSes". Apparently, Windows 8 and below are not supported anymore, but please keep in mind that the unsupported systems have long been out of support and _do not_ constitute a significant number of usages, see, e.g., https://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/755472/4203c8b7-6493-4cf7-b075-7c4227615e26)

**Comment by Phillipus** [comment] 2024-06-26 08:12
A user: "This is a critical issue!"
Also a user: "Our company is using unsupported OSes"

:-)

**Comment by akurtakov** [comment] 2024-07-04 14:49
As per https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2012 Oct 10, 2023 is end of support except for "Extended Security Update" but eclipse has always been considering the general date and not the "extended" as some of these literally never end and the project doesn't have the ability to advance and keep such compatibility.

**Comment by laeubi** [comment] 2024-07-06 10:05
> I totally agree here. At the same time, we (DBeaver tech support) have just received an angry report from a customer about DBeaver 24.1 not launching on Windows Server 2012, which is supported until October 2026.

One solution would be to let DBeaver 24.1 using Eclipse 2024-03, increase the version to DBeaver 25 and use 2024-06 from there on with a clear hint it does need Win 10+

**Comment by Camiller957** [comment] 2024-07-22 09:56
Windows Server 2012 also encountered the same error. Does DBeaver software support Windows Server 2012?

**Comment by HWesterhof** [comment] 2024-07-22 11:15
Not supporting end of life OS'es is one thing, but not warning people before an upgrade is maybe fixable. My DBeaver client told me to upgrade to the latest version, but I'm on Windows Server 2012 R2 (for...reasons). So in my opinion the client should not suggest upgrading to a version that will break the installation.

**Comment by greenozon** [comment] 2024-07-22 11:17
Windows Server 2012 is supported officially 2 more years (up to late 2026)
https://endoflife.date/windows-server

why banning it before EOL???

**Comment by HeikoKlare** [comment] 2024-07-23 08:44
@greenozon I would like to kindly ask you to stop spamming bold statement and read the explanations we have given so far instead. No one here actively _bans_ some OS (version). We only try to make progress, keeping SWT alive and adopting new necessary features. Losing support for older OSes is not a goal but may only be a side effect of these efforts. Please consider contributing to the Eclipse project to ensure that (implicit) OS version constraints are properly handled, checked and considered in a prerequsites check for (automatic) updates of products like the IDE.
I agree with @HWesterhof that the goal of any efforts with respect to this issue should be to make version requirements more explicit and, in particular, checked as preconditions for automated updates.

**Comment by t00** [comment] 2024-10-18 09:18
The issue happens on the most recent update of Windows Server 2016 which is still supported by Microsoft:

```
Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	C:\Program Files\DBeaver\swt-win32-4966r5.dll: The specified procedure could not be found
	no swt-win32 in java.library.path: 
```

**Comment by Phillipus** [comment] 2024-10-18 09:22
> What is the last working version to be used which does not have DPI and GetVersion() changes?

It seems that Windows Server 2022 is the best bet. From other reports Windows Server 2016 and 2019 do not support these API functions in spite of the documentation suggesting that they do.

See https://github.com/eclipse-platform/eclipse.platform.swt/issues/1500

**Comment by t00** [comment] 2024-10-18 09:24
I just checked [2024-09-01](https://dbeaver.io/2024/09/01/dbeaver-24-2/) works fine and for now I will stick to it until we upgrade to docker hosting. Many thanks for a quick reply.
