### ISSUE TITLE
Hovers are not showing for java in latest i-builds

### ISSUE THREAD

**Issue by gayanper** [eclipse-platform/eclipse.platform.swt#249] opened 2022-07-10 20:00 UTC
**Describe the bug**
No hover popups in java editor

**To Reproduce**
Hover over java element for javadoc or source hover. The following error happens in the error log
```
java.lang.NullPointerException: Cannot read field "height" because "rect" is null
	at org.eclipse.swt.graphics.TextLayout.getLineBounds(TextLayout.java:1010)
	at org.eclipse.jface.internal.text.html.BrowserInformationControl.computeSizeHint(BrowserInformationControl.java:447)
	at org.eclipse.jface.text.AbstractInformationControlManager.internalShowInformationControl(AbstractInformationControlManager.java:1174)
	at org.eclipse.jface.text.AbstractInformationControlManager.presentInformation(AbstractInformationControlManager.java:1120)
	at org.eclipse.jface.text.AbstractHoverInformationControlManager.presentInformation(AbstractHoverInformationControlManager.java:884)
	at org.eclipse.jface.text.TextViewerHoverManager.doPresentInformation(TextViewerHoverManager.java:237)
	at org.eclipse.jface.text.TextViewerHoverManager.lambda$3(TextViewerHoverManager.java:227)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4345)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3968)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

**Expected behavior**
The hover should be shown.

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [ ] Linux
- - [x] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)3. 
12.4 

4. JRE/JDK version
17 

**Version since**
Version: 2022-06 (4.25)
Build id: I20220709-1800

**Workaround (or) Additional context**

**Comment by Phillipus** [comment] 2022-07-10 21:14
If this is Mac only then it might be a regression from:

https://github.com/eclipse-platform/eclipse.platform.swt/commit/51dc75e726e4995ad8cd29150f90c993489b43d7

**Comment by Phillipus** [comment] 2022-07-11 10:40
Ignore last comment, it doesn't work.

**Comment by lshanmug** [comment] 2022-07-11 10:44
Thanks for investigating Phil.

The problem here is that the original commit fixed the line count and the lineOffsets taking into account the trailing new line and a but the corresponding rect for the new line is not set in the lineBounds and is null.

**Comment by Phillipus** [comment] 2022-07-11 10:48
OK, thanks. I don't think I can figure out a fix for this one.

**Comment by lshanmug** [comment] 2022-07-11 10:51
Since Mac API NSTextLayoutManager.lineFragmentUsedRectForGlyphAtIndex() doesn't account for the trailing '\n', getting the bounds would be manual and error prone. I'm considering reverting the fix as the original behavior was inconsistent with Windows and caused test failure but AFAIK didn't cause any problems in the IDE.

**Comment by Phillipus** [comment] 2022-07-11 10:54
Well, it's been like this for many years, and only a change in the JUnit test showed a difference in `getLineOffsets` on Mac. Perhaps the JUnit test should be changed to allow for different behaviour on Mac?

**Comment by lshanmug** [comment] 2022-07-11 17:18
Reverted the original commit. Will update the failing JUnit test in separate PR.

**Closed by lshanmug** 2022-07-11 17:18 UTC
Labels: regression, macOS

**Comment by lshanmug** [comment] 2022-07-13 07:32
> Well, it's been like this for many years, and only a change in the JUnit test showed a difference in `getLineOffsets` on Mac. Perhaps the JUnit test should be changed to allow for different behaviour on Mac?

Done via https://github.com/eclipse-platform/eclipse.platform.swt/pull/255

**Comment by lshanmug** [comment] 2022-07-13 10:47
> The Javadoc for Mac version of `TextLayout#getLineOffsets` says:
> 
> > Returns the line offsets. Each value in the array is the offset for the first character in a line except for the last value, which contains the length of the text.
> 
> Should it be changed to say what actually is returned on Mac? Something like:
> 
> > Returns the line offsets. Each value in the array is the offset for the first character in a line except for the last value, which contains the length of the text.
> > Note that if the last character is a newline character the last value containing the length of the text is not returned. This differs from the Linux and Windows implementations.

On Mac too, the last value contains the length of the text. The difference is that the offset for the last empty line (line after the last newline) is not returned in the array.
