### ISSUE TITLE
Using vertical and horizontal Composite does not work under macOS anymore

### ISSUE THREAD

**Issue by tkg1-de** [eclipse-platform/eclipse.platform.swt#1082] opened 2024-03-04 22:03 UTC
I've written a complex program working fine for several years under macOS (Intel) and Windows as well. But after upgrading to newest Java 11 it doesn't work anymore on macOS. So I used the latest SWT 4.30 together with Java 17 (OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)). It doesn't work. On Windows everything is fine. On macOS the second horizontal Composite is not visible. I created a simple test class showing the problem.
![SimpleSWTCompositeTest-macOS](https://github.com/eclipse-platform/eclipse.platform.swt/assets/162214939/9157efa2-38fb-49e6-bfc8-725f3469c1b3)
![SimpleSWTCompositeTest-Windows](https://github.com/eclipse-platform/eclipse.platform.swt/assets/162214939/fd1e146f-729a-4dd8-9f0d-7ff9b2e4dabf)

This is the source code:
package main;

import org.eclipse.swt.SWT;
import org.eclipse.swt.layout.RowData;
import org.eclipse.swt.layout.RowLayout;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Event;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.Listener;
import org.eclipse.swt.widgets.Shell;

public class SimpleSWTCompositeTest {

	public static void main(String[] args) {
		Display.setAppName("SimpleSWTCompositeTest");
		Display display = new Display();

		Shell shell = new Shell(display, SWT.SHELL_TRIM | SWT.CENTER);
		//shell.setSize(930, 670);

		shell.addListener(SWT.Close, new Listener() {
			public void handleEvent(Event event) {
				shell.getDisplay().dispose();
				System.exit(0);
			}
		});

		RowLayout shellLayout = new RowLayout(SWT.VERTICAL);
		shellLayout.marginTop = 7;
		shellLayout.marginBottom = 7;
		shellLayout.marginLeft = 3;
		shellLayout.marginRight = 3;
		shellLayout.spacing = 0;
		shell.setLayout(shellLayout);

		Composite headerComposite1 = new Composite(shell, SWT.NONE);
		RowLayout headerLayout1 = new RowLayout(SWT.HORIZONTAL);
		headerLayout1.marginTop = 10;
		headerLayout1.marginBottom = 10;
		headerLayout1.marginLeft = 5;
		headerLayout1.marginRight = 5;
		headerLayout1.spacing = 10;
		headerComposite1.setLayout(headerLayout1);

		Label testText11 = new Label(headerComposite1, SWT.WRAP);
		testText11.setText("Dies ist ein Test-Text! 11");
		RowData statusData11 = new RowData(203, 32);
		testText11.setLayoutData(statusData11);

		Label testText12 = new Label(headerComposite1, SWT.WRAP);
		testText12.setText("Dies ist ein Test-Text! 12");
		RowData statusData12 = new RowData(203, 32);
		testText12.setLayoutData(statusData12);

		Composite headerComposite2 = new Composite(shell, SWT.NONE);
		RowLayout headerLayout2 = new RowLayout(SWT.HORIZONTAL);
		headerLayout2.marginTop = 10;
		headerLayout2.marginBottom = 10;
		headerLayout2.marginLeft = 5;
		headerLayout2.marginRight = 5;
		headerLayout2.spacing = 10;
		headerComposite2.setLayout(headerLayout2);

		Label testText21 = new Label(headerComposite2, SWT.WRAP);
		testText21.setText("Test-Text! 21");
		RowData statusData21 = new RowData(132, 32);
		testText21.setLayoutData(statusData21);

		Label testText22 = new Label(headerComposite2, SWT.WRAP);
		testText22.setText("Test-Text! 22");
		RowData statusData22 = new RowData(132, 32);
		testText22.setLayoutData(statusData22);

		Label testText23 = new Label(headerComposite2, SWT.WRAP);
		testText23.setText("Test-Text! 23");
		RowData statusData23 = new RowData(132, 32);
		testText23.setLayoutData(statusData23);
		
		shell.setText("SimpleSWTCompositeTest");
		shell.pack();
		shell.open();

		while (!shell.isDisposed() ) {
			if (!display.readAndDispatch())
				display.sleep();
		}		
		
		display.dispose();
	}
}

**Comment by iloveeclipse** [comment] 2024-03-04 22:05
Most likely duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/1012

**Comment by Phillipus** [comment] 2024-03-04 22:41
> Most likely duplicate of #1012

Yes, it is. I tested the snippet with Temurin-17.0.10+7 and reproduced the issue. I applied #1081 and ran the snippet again and it was OK.

**Comment by Phillipus** [comment] 2024-03-04 22:44
@tkg1-de Please can you confirm macOS version and whether you use Intel or Silicon Mac.

**Comment by jukzi** [comment] 2024-03-05 07:23
closing as duplicate

**Comment by laeubi** [comment] 2024-03-05 07:33
Please use this (also offered as a saved reply by github) to mark / close tickets as duplicate:

`Duplicate of #<number>`

**Comment by laeubi** [comment] 2024-03-05 07:33
Duplicate of #1081

**Closed by laeubi** 2024-03-05 07:33 UTC
Labels: duplicate, macOS

**Comment by tkg1-de** [comment] 2024-03-05 08:02
Yes, it seems really to be a duplicate of #1012. So closing is O.K.

I use an Intel Mac (MacBook Pro 13-inch, 2019, Two Thunderbolt 3 ports). macOS 14.3.1 (latest version at this moment)

Thanks a lot!

**Comment by Phillipus** [comment] 2024-03-05 09:19
> I use an Intel Mac...macOS 14.3.1

Thanks. I wanted to confirm this bug occurs on Intel as well as ARM.
