### ISSUE TITLE
libswt-cocoa-4952r11.jnilib can't be open - Apple Sandbox app error

### ISSUE THREAD

**Issue by Saibion** [eclipse-platform/eclipse.platform.swt#357] opened 2022-08-30 21:11 UTC
Environment:
Eclipse: Version: 2022-06 (4.24.0), Build id: 20220609-1112
org.eclipse.swt.cocoa.macosx.x86_64_3.120.0.v20220530-1036.jar
     libswt-cocoa-4952r11.jnilib
org.eclipse.swt_3.120.0.v20220530-1036.jar
JRE - 11.0.16
OS: macOS 12.5.1

Problem occurs from within an Apple sandbox application when launched in macOS 12.5.1 the latest Apple release version.
Our Eclipse RCP maven built application submitted to App Store Connect application review report the following error:

![Screen+Shot+2022-08-26+at+1 39 16+PM png](https://user-images.githubusercontent.com/109222362/187543529-f7f1676c-c1ae-4fbd-965e-49084b8ef694.jpeg)

This error was not reported in macOS 12.4. Earlier versions of this application using the same SWT cocoa version and containing the same set of plugins successfully passed the review process.  Our only guess is that the code in question was slipping by the gatekeeper in earlier macOS versions.

Verifying the signature produces the following result:
```
command: codesign -dv --verbose=4 libswt-cocoa-4952r11.jnilib  

Executable=/[location]/org.eclipse.swt.cocoa.macosx.x86_64_3.120.0.v20220530-1036/libswt-cocoa-4952r11.jnilib
Identifier=SigningServlet-611112540525402197-unsigned-libswt-cocoa-4952r11
Format=Mach-O thin (x86_64)
CodeDirectory v=20500 size=4715 flags=0x10000(runtime) hashes=140+2 location=embedded
VersionPlatform=1
VersionMin=657920
VersionSDK=721152
Hash type=sha256 size=32
CandidateCDHash sha1=7612a3b62dbd4f8fb0572471fcc064e4df12a9dc
CandidateCDHashFull sha1=7612a3b62dbd4f8fb0572471fcc064e4df12a9dc
CandidateCDHash sha256=de56aaf2fa66a0c00d54fb3fb25cb8477d530a5e
CandidateCDHashFull sha256=de56aaf2fa66a0c00d54fb3fb25cb8477d530a5e091559330f502c43850dec4b
Hash choices=sha1,sha256
CMSDigest=e719676fe557543c24e3cebf7c0183dbf8a9e349ab793581cb721bbe7efacc66
CMSDigestType=2
Page size=4096
CDHash=de56aaf2fa66a0c00d54fb3fb25cb8477d530a5e
Signature size=9079
Authority=Developer ID Application: Eclipse Foundation, Inc. (JCDTMS22B4)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=May 9, 2022 at 5:05:59 PM
Info.plist=not bound
TeamIdentifier=JCDTMS22B4
Runtime Version=11.1.0
Sealed Resources=none
Internal requirements count=1 size=224
```
It may be important to note that the error does not occur when the application is signed and notarized for distribution other than Apples App Store. CORGROUP has been looking at this since reported on August 26th without effect. Thank you for your time and consideration.

Be well,
Ralph

**Comment by SyntevoAlex** [comment] 2022-09-01 17:09
Duplicate of #269

**Closed** 2022-09-01 18:08 UTC
Labels: macOS
