### ISSUE TITLE
LocationListener's "cancel" not effective with Edge, for 3xx redirects

### ISSUE THREAD

**Issue by benjaminr-ps** [eclipse-platform/eclipse.platform.swt#738] opened 2023-07-12 06:38 UTC
**Describe the bug**
We have implemented the LocationListener interface, which has to cancel the redirect navigation, once a particular URL should be navigated/redirected to.
(For handling a OAuth 2.0/OpenIdConnect login via native browser)

**To Reproduce**
1. Implement LocationListener interface, especially "changing" function
3. Register to Browser object.
4. Set authorization URL
5. (Let redirect happen, to login page)
6. Enter credentials
7. (Get redirected by Identity Provider)

**Expected behavior**
LocationListener.changing event can interfer the navigation.

**Actual behavior**
LocationListener.changing event is triggered, but browser navigated, already.
No chance to cancel the naviation.

**Screenshots**
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/16348067/bfbc608c-542e-4b00-9cba-a2fb02f6f2a5)

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

9. Additional OS info (e.g. OS version, Linux Desktop, etc)
Windows 10
Edge 114.0.1823.67
org.eclipse.swt.win32.win32.x86_64: 3.124.0.v20230523-1044

10. JRE/JDK version
 JDK 17.0.7

**Workaround (or) Additional context**
No workaround

**Comment by sratz** [comment] 2024-11-12 05:00
I cannot reproduce this.

See the following snippet:

```java
import org.eclipse.swt.*;
import org.eclipse.swt.browser.*;
import org.eclipse.swt.layout.*;
import org.eclipse.swt.widgets.*;

public class Edge302CancelInChanging {

	public static void main(String[] args) {
		Display display = new Display();
		Shell shell = new Shell(display);
		shell.setLayout(new FillLayout());
		Browser browser = new Browser(shell, SWT.EDGE);
		browser.addLocationListener(new LocationListener() {

			@Override
			public void changing(LocationEvent event) {
				System.out.println("Changing: " + event.location);
				if (event.location.equals("https://www.eclipse.org/")) {
					event.doit = false;
				}
			}

			@Override
			public void changed(LocationEvent event) {
				System.out.println("Changed: " + event.location);
			}
		});
		browser.setUrl("https://httpbin.org/redirect-to?url=https%3A%2F%2Fwww.eclipse.org/&status_code=302");
		shell.open();
		while (!shell.isDisposed()) {
			if (!display.readAndDispatch())
				display.sleep();
		}
		display.dispose();
	}

}
```

The redirect is canceled successfully.

I am closing this issue as not reproducible.

In case this still is an issue, please feel free to re-open. In that case it would help if you could provide a way to reproduce this problem end-to-end.

**Closed by sratz** 2024-11-12 05:00 UTC
Labels: Windows, edge
