### ISSUE TITLE
Browser tests are failing

### ISSUE THREAD

**Issue by basilevs** [eclipse-platform/eclipse.platform.swt#1613] opened 2024-11-22 15:18 UTC
Following tests [consistently fail on Linux in CI](https://github.com/eclipse-platform/eclipse.platform.swt/actions/runs/11825012703/job/32947826383):

- Test_org_eclipse_swt_browser_Browser.test_OpenWindowListener_open_ChildPopup
- Test_org_eclipse_swt_browser_Browser.test_OpenWindow_Progress_Listener_ValidateEventOrder
-  Test_org_eclipse_swt_browser_Browser.test_VisibilityWindowListener_eventSize

Blocks #678

**Comment by akurtakov** [comment] 2024-11-22 15:39
Duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/1564

**Closed by akurtakov** 2024-11-22 15:39 UTC
