### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Could not load SWT library

### ISSUE THREAD

**Issue by Padawan8** [eclipse-platform/eclipse.platform.swt#1601] opened 2024-11-20 09:53 UTC
We managed to install the latest Eclipse platform on our windows server a month ago. A server upgrade was done which removed our previous installation. Now when trying to install it again, it fails with the error message "java.lang.UnsatisfiedLinkError: Could not load SWT library 
Reasons: 
	C:\DownloadSAP\eclipse-committers_64\eclipse\configuration\org.eclipse.osgi\480\0\.cp\swt-win32-4966r5.dll: La procédure spécifiée est introuvable
	no swt-win32 in java.library.path: C:\DownloadSAP\eclipse-committers_64\eclipse;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Program Files\OpenSSL-Win64\bin;C:\Users\nyumuyantu.theophile\AppData\Local\Microsoft\WindowsApps;;.
	no swt in java.library.path: C:\DownloadSAP\eclipse-committers_64\eclipse;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Program Files\OpenSSL-Win64\bin;C:\Users\nyumuyantu.theophile\AppData\Local\Microsoft\WindowsApps;;.
	C:\Users\nyumuyantu.theophile\.swt\lib\win32\x86_64\swt-win32-4966r5.dll: La procédure spécifiée est introuvable
	Can't load library: C:\Users\nyumuyantu.theophile\.swt\lib\win32\x86_64\swt-win32.dll
	Can't load library: C:\Users\nyumuyantu.theophile\.swt\lib\win32\x86_64\swt.dll
	C:\Users\nyumuyantu.theophile\.swt\lib\win32\x86_64\swt-win32-4966r5.dll: La procédure spécifiée est introuvable".

Our current windows server version is Windows 2016, java is JDK 23

Many thanks

**Comment by sratz** [comment] 2024-11-20 10:02
This is a duplicate of #1500. It's a known issue in Eclipse 2024-09, which will be fixed by  #1568 with Eclipse 2024-12.

**Closed by sratz** 2024-11-20 10:02 UTC
