### ISSUE TITLE
Wayland support in experimental state despite being introduced in stable releases

### ISSUE THREAD

**Issue by Ricky-Tigg** [eclipse-platform/eclipse.platform.swt#639] opened 2023-04-20 13:20 UTC
_Eclipse IDE for Java Developers_ | **v.:** 2023-03 (4.27.0) | **Build ID:** 20230309-1520 | **Linux kernel v.:** 6.2 | **Gnome v.:** 44.0

Hello. What can be learned from a **first** usage? Well. The Wayland support appears to be so low that it is reasonable to interpret it as being still in **experimental** state. What did you think that could be most likely to happen with a fair quality software seeking user. The first use shall also be the last. That is what an experience as bad as it is can do.

Observations:
- Some windows part of the operation covered by the _Eclipse installer_ are **missing their title bar**.
- Those windows **cannot be moved nor resized according to any axe**. As a result, with my current screen resolutions, the whole content of some windows could not be exhibited; for instance the _Install_ element which then prevented the installation of this application. I had to switch to _Gnome on X.org_ in order to get it installed.

Once installed, switching back to _Wayland_ in order to figure out whether the experience can go worse. And guess; it can.
```
$ ./eclipse/java-2023-032/eclipse/eclipse
WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.vector
13:55:11.879 [main] DEBUG org.eclipse.m2e.core.internal.project.registry.ProjectRegistryRefreshJob - Queued refresh request: []
```
- Unlike applications Firefox, LibreOffice and many others that are able to fill the **whole screen's surface**, this application is not yet. Despite the capability of optimization of the workspace is one of the key requirement of modern software in order to provide professional user experience.. 

Since there is no choice but to learn this application in bad working-condition, then let's keep on testing so.

In _Help_ menu
- Select _Check for update_ | Resultant window displayed has a title bar. Attempts to move that window invariably fails; Eventually it moves the main window instead, which triigers in terminal:

`(Eclipse:22582): Gdk-WARNING **: 12:17:37.509: Tried to unmap the parent of a popup`

- Select _Eclipse Marketplace_ | Resultant window, which has a title bar, can be moved. This selection triggers in terminal multiple iterations of this message:
```
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
```
- Open the rolling-menu containing the option _All markets_ and click somewhere outside the area listing the options. | **No effect**; the rolling menu remains open. Pressing <kbd>esc</kbd> does close it.

- Enlarge that window by double-clicking its title bar so it fills the available workspace. Within it, select _Help_ | That results in moving the window to the right side, while the _Help_ panel is out of screen.
- Once the panel has been made visible, double-click the window's title bar | That triggers the **disappearance** of that _Help_ panel.

At last, one more test before switching to X11.
- **Next attempts** to get that panel exhibited in that session invariably fail. 

 Obviously there is no need to be endowed with any talent to guess that this augurs an incalculable number of issues with those functionalities not tested here, and for reason. Best practices and guideline in regard to software release do exist for a reason; **to be observed**.  Now since this aspect was ignored by developers, all those issues that should have been resolved while the software was in experimental state, have finally reached stable releases. Be sure from now to take it into account.

**Comment by akurtakov** [comment] 2023-04-20 13:38
First of all - this is volunteer driven project so you're more than welcome to show us how to do things ***proper*** . 

Now more seriously, Fedora Desktop users have been using Eclipse on Wayland with Adwaita theme by default for years already without such issues so please share which Linux distribution you're using, which Gtk theme, any additional customizations done and so on. Once this information is known it would remain to be seen who (if anyone) is interested is in supporting this combination. There are really M(Gtk)*N(Gtk theme)*P(DE)*Q(WM)*P(distro hacks) combinations and some of these end up in having to fix what you face pile.

**Comment by akurtakov** [comment] 2023-04-20 13:43
![image](https://user-images.githubusercontent.com/574788/233384613-10c703ac-989c-4fdf-aaea-3df4f6304386.png)
This is my Fedora 38 Gnome Wayland Adwaita Eclipse 4.28 I-bulid running. Please attach a screenshot of broken state for you to visualize the problem better.

**Comment by merks** [comment] 2023-04-20 15:49
While I can 100% sympathize with how frustrating it is to have a thoroughly negative experience as you have had, I want to remind you that we do have a code of conduct for our community:

https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php

The off-putting tone in which you vent your frustration falls below the bar of what we normally and reasonably expect in our community.   Let's try to move forward from that.  Please help us help you by sharing the detailed information that is needed to understand why you see these problems while other people, even those on Linux, do not see those same problems.  There are many people here who can try to help you.  Being nice doesn't cost anything.

**Comment by Ricky-Tigg** [comment] 2023-04-21 08:46
_Calm down!_ You are not at home here. Could i expect that you would have a surprise, for me. Or was it just for me? It appears that **we won't speak here the same language**, whatever it may be called. Then what follows won't be understood neither.

We red, we know now. Hiding poor education and own weaknesses behind words; fine, that is you, but for me, no thanks. Since keeping the present report opened or closing it, is no more relevant for any readers being non-developer, i leave you waste your time in family.

At last since you seek for being remembered as **ambassadors** of this project, we can observe your barely learned your lesson; _Things have consequences, not the ones we expect though_ How do you dare asking for donation while abusing of your positions? Of course you won't understand that.

For the record, as it could easily be guessed, it was _Fedora Desktop_ last edition, thus 38, **default configuration kept** and java-17-openjdk and java-17-openjdk-headless installed. I leave you the last words. We can understand you shall enjoy it to be so.

**Comment by merks** [comment] 2023-04-21 09:03
Wow that’s very personal. I lost count of the number of direct personal insults.  I have to wonder if this approach ever produces the intended results. I suppose that depends on the intent…

**Comment by iloveeclipse** [comment] 2023-04-21 13:59
> Wow that’s very personal. I lost count of the number of direct personal insults. I have to wonder if this approach ever produces the intended results. I suppose that depends on the intent…

Thanks Ed, I couldn't say better.

@Ricky-Tigg : please avoid comments with such inappropriate style if you want to be heard here.

**Comment by merks** [comment] 2023-07-18 13:58
Someone complained about the Installer working poorly on Wayland as well:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=582201

I don't think Oomph can do better than the Platform though.  Does anyone know which virtual box image I can host on Windows in order to test how the Platform and the Installer work with Wayland?

**Comment by akurtakov** [comment] 2023-07-18 14:00
Just pick the latest Fedora 38 Gnome and start Eclipse on it. It will default to Wayland if you change nothing.

**Comment by Ealrann** [comment] 2023-07-18 14:08
Sorry, but I wont change my OS just for Eclipse, and I cannot change due to my activities. Also, I'd like to mention that Archlinux is far more used than Fedora. The statistics websites generally don't know how to count Archlinux, but when they do it's number one (here: https://linuxiac.com/most-popular-linux-distros-according-to-reddit/ and here: https://www.phoronix.com/news/Steam-Survey-May-2022).

**Comment by akurtakov** [comment] 2023-07-18 14:14
@Ealrann I have never meant to suggest you change your OS. 
My reply was for @merks who wants to test things and Fedora is what majority of the developers that worked on SWT lately have been using.

**Comment by Ealrann** [comment] 2023-07-18 14:18
Ok, my bad, I didn't understood that

**Comment by merks** [comment] 2023-07-18 14:34
@Ealrann 

Sorry for hijacking the topic.  I want to do my part of to help fix problem, but I develop on Windows 10, so it's more challenging to help...

**Comment by eddy-geek** [comment] 2023-07-26 13:54
As an end-user hitting this issue, the workaround to run an SWT app in the (legacy) XWayland mode is to add `GDK_BACKEND=X11` at the start of the command to run your app.

I think this would be nice to have in the [faq](https://www.eclipse.org/swt/faq.php).

**Comment by euphi** [comment] 2023-10-24 21:54
> As an end-user hitting this issue, the workaround to run an SWT app in the (legacy) XWayland mode is to add `GDK_BACKEND=X11` at the start of the command to run your app.
> 
> I think this would be nice to have in the [faq](https://www.eclipse.org/swt/faq.php). 

You should use `GDK_BACKEND=x11` (lower case x). 
But thanks for the hint - I tried XDG_SESSION_TYPE, but this seems to not change from wayland to x11. With x11 backend eclipse performance increases significantly.
However, it also wasn't that bad with wayland. Most annoying with wayland was the unresponsive movement of tabs / views. Scrolling was laggy, but barely acceptable.

_(current (stable) Gentoo Linux, wayland 5.1, X.org 23.1.2, openjdk 17.0.6)._

**Comment by mickaelistria** [comment] 2023-12-08 13:23
@Ricky-Tigg yes, I think it's best to close it and instead of specific tickets for each issue, focusing on the technical aspect (steps to reproduce, known workarounds, tried or suggested fixes...), which are usually easier to turn into action.

**Closed by mickaelistria** 2023-12-08 13:23 UTC
