### ISSUE TITLE
[GTK] Disabled toolbar icons and button images are double size on hi-res screen

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/eclipse.platform.swt#315] opened 2022-08-14 11:29 UTC
**Describe the bug**
I'm bringing this over from https://bugs.eclipse.org/bugs/show_bug.cgi?id=575492 as the problem still exists.

Disabled images in buttons and toolbar items are the wrong size when DPI scaling is at 200%

**To Reproduce**
Run Snippet at 200% scaling to see that the disabled button image is scaled incorrectly and is too big and off-centred.

**Expected behavior**
The disabled button image should be scaled correctly when DPI is at 200% scale.

**Screenshots**
Disabled button at 100% scale:

![100-scale](https://user-images.githubusercontent.com/600504/184534518-99122bbc-8f81-49f7-a4e3-08584b02e771.png)

Disabled button at 200% scale:

![200-scale](https://user-images.githubusercontent.com/600504/184534526-6157d895-462f-4732-87fb-91627b2723da.png)

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [x] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
Linux Mint Cinnamon X11. Didn't test on Wayland.

3. JRE/JDK version
AdoptOpeJDK 11.0.15
 
**Version since**
Worked OK in Eclipse 4.15, but not since

**Comment by Phillipus** [comment] 2022-08-14 11:31
Snippet to reproduce:

```java
import org.eclipse.swt.SWT;
import org.eclipse.swt.graphics.Image;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;

public class DisabledButtonImageTest {

    public static void main(String[] args) {
        Display display = new Display();
        Shell shell = new Shell(display);
        shell.setLayout(new GridLayout());
        shell.setText("Button Image");

        Image image = display.getSystemImage(SWT.ICON_WARNING);

        Button button = new Button(shell, SWT.FLAT);
        button.setImage(image);
        button.setEnabled(false);

        shell.open();
        while(!shell.isDisposed()) {
            if(!display.readAndDispatch()) display.sleep();
        }
        display.dispose();
    }
}
```

To test this at 200% scaling either use a Hi-DPI monitor or set an Environment Variable `GDK_SCALE=2` in the launch configuration.

**Comment by joel-majano** [comment] 2022-08-18 16:27
Reproduced the bug in XWayland (Wayland using GDK_BACKEND=x11). This bug does not affect Wayland itself.

**Comment by AlexisDrogoul** [comment] 2022-08-21 15:19
Affects Ubuntu with Eclipse 2022-03 (4.23) (see https://github.com/gama-platform/gama/issues/3460). Disabled icons for buttons in the Coolbar (contributed by `plugin.xml`) and regular buttons are doubled in size with a 2x scale/HiDPI setting. The same happens to `ToolItem`s unless a disabled icon is passed to them.

**Comment by joel-majano** [comment] 2022-08-21 20:58
Looking at this some more, to create the disabled image we copy from the image we get using getSystemImage. In this case, the icon is already scaled when it is first created. When creating the copy in the Image constructor, it copies the currentDeviceZoom and performs another scale up using cairo_surface_set_device_scale. This is why the image scaled 4x.

The fix is to check if _DPIUtil.getDeviceZoom()_ is equal to the copied _currentDeviceZoom_, and if it is, skip the scaling. I have a patch ready which I will upload in the morning eastern time.

**Comment by Phillipus** [comment] 2022-08-22 08:04
Might be a clue in this bug:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=568407

Maybe the fix for that bug wasn't applied to disabled images?

**Comment by joel-majano** [comment] 2022-08-22 14:24
I was able to find the issue on the toolbar icon size; it was due to a bug in ImageList. Pushed the fix.

**Closed** 2022-09-03 09:42 UTC
Labels: Linux/GTK
