### ISSUE TITLE
Splash screen is reversed

### ISSUE THREAD

**Issue by vadym-yusanenko** [eclipse-platform/eclipse.platform.swt#830] opened 2023-10-06 18:02 UTC
**Describe the bug**
Splash screen is reversed (at first it appears correctly and after a couple of second gets reversed) on AArch64 (Apple Silicon) since (at least) version 2023-09.

**To Reproduce**
Open Eclipse on macOS Sonoma and pay attention to splash screen during load process. 

**Expected behavior**
Splash screen is shown with no glitches.

**Screenshots**
<img width="459" alt="Screenshot 2023-10-06 at 20 53 59" src="https://github.com/eclipse-platform/eclipse.platform.swt/assets/748882/c84e4fc6-8fa3-4d9f-aa54-bc077523202a">

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [ ] Linux
- - [x] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
OS: macOS Sonoma 14.0 (23A344)

3. JRE/JDK version
org.eclipse.justj.openjdk.hotspot.jre.full.macosx.aarch64_20.0.2.v20230801-2057
 
**Version since**
 2023-09 (4.29)

**Workaround (or) Additional context**
No known workarounds found

**Comment by yusanenko-vadim** [comment] 2023-10-06 18:05
*** Date: Friday, October 6, 2023, 9:00:28 PM Eastern European Summer Time

*** Platform Details:

*** System properties:
applicationXMI=org.eclipse.ui.workbench/LegacyIDE.e4xmi
ds.delayed.keepInstances=true
ds.delayed.keepInstances.default=true
eclipse.application=org.eclipse.ui.ide.workbench
eclipse.buildId=4.29.0.I20230903-1000
eclipse.commands=-os
macosx
-ws
cocoa
-arch
aarch64
-showsplash
-launcher
/Applications/ide-latest-released/Eclipse.app/Contents/MacOS/eclipse
-name
Eclipse
--launcher.library
/Users/vadymyusanenko/.p2/pool/plugins/org.eclipse.equinox.launcher.cocoa.macosx.aarch64_1.2.700.v20221108-1024/eclipse_11801.so
-startup
/Applications/ide-latest-released/Eclipse.app/Contents/MacOS//../Eclipse/plugins/org.eclipse.equinox.launcher_1.6.500.v20230717-2134.jar
--launcher.appendVmargs
-keyring
/Users/vadymyusanenko/.eclipse_keyring
-vm
/Users/vadymyusanenko/.p2/pool/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.macosx.aarch64_20.0.2.v20230801-2057/jre/lib/libjli.dylib
eclipse.home.location=file:/Applications/ide-latest-released/Eclipse.app/Contents/Eclipse/
eclipse.launcher=/Applications/ide-latest-released/Eclipse.app/Contents/MacOS/eclipse
eclipse.launcher.name=Eclipse
eclipse.p2.data.area=file:/Users/vadymyusanenko/.p2/
eclipse.p2.max.threads=10
eclipse.p2.profile=_Applications_ide-latest-released_Eclipse.app_Contents_Eclipse
eclipse.product=org.eclipse.platform.ide
eclipse.startTime=1696614837435
eclipse.stateSaveDelayInterval=30000
eclipse.vm=/Users/vadymyusanenko/.p2/pool/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.macosx.aarch64_20.0.2.v20230801-2057/jre/lib/libjli.dylib
eclipse.vmargs=-Declipse.p2.max.threads=10
-Doomph.update.url=https://download.eclipse.org/oomph/updates/milestone/latest
-Doomph.redirection.index.redirection=index:/->http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/setups/
--add-opens=java.base/java.lang=ALL-UNNAMED
-Djava.security.manager=allow
-Dosgi.requiredJavaVersion=17
-Dosgi.dataAreaRequiresExplicitInit=true
-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true
-Xms40m
-Xmx512m
--add-modules=ALL-SYSTEM
-Dorg.slf4j.simpleLogger.defaultLogLevel=off
-Xdock:icon=../Resources/Eclipse.icns
-XstartOnFirstThread
-Dorg.eclipse.swt.internal.carbon.smallFonts
-Djava.class.path=/Applications/ide-latest-released/Eclipse.app/Contents/MacOS//../Eclipse/plugins/org.eclipse.equinox.launcher_1.6.500.v20230717-2134.jar
equinox.init.uuid=true
file.encoding=UTF-8
file.separator=/
ftp.nonProxyHosts=local|*.local|169.254/16|*.169.254/16
gosh.args=--nointeractive
java.class.path=/Applications/ide-latest-released/Eclipse.app/Contents/MacOS//../Eclipse/plugins/org.eclipse.equinox.launcher_1.6.500.v20230717-2134.jar
java.class.version=64.0
java.home=/Users/vadymyusanenko/.p2/pool/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.macosx.aarch64_20.0.2.v20230801-2057/jre
java.io.tmpdir=/var/folders/2f/0pwq2gwd2tdfl6vq00ys_l0m0000gn/T/
java.library.path=/Users/vadymyusanenko/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
java.runtime.name=OpenJDK Runtime Environment
java.runtime.version=20.0.2+9
java.security.manager=allow
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=20
java.vendor=Eclipse Adoptium
java.vendor.url=https://adoptium.net/
java.vendor.url.bug=https://github.com/adoptium/adoptium-support/issues
java.vendor.version=Temurin-20.0.2+9
java.version=20.0.2
java.version.date=2023-07-18
java.vm.compressedOopsMode=Zero based
java.vm.info=mixed mode
java.vm.name=OpenJDK 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=20
java.vm.vendor=Eclipse Adoptium
java.vm.version=20.0.2+9
jdk.debug=release
line.separator=
native.encoding=UTF-8
oomph.redirection.index.redirection=index:/->http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/setups/
oomph.update.url=https://download.eclipse.org/oomph/updates/milestone/latest
org.eclipse.equinox.launcher.splash.location=/Users/vadymyusanenko/.p2/pool/plugins/org.eclipse.platform_4.29.0.v20230903-1000/splash.png
org.eclipse.equinox.simpleconfigurator.configUrl=file:org.eclipse.equinox.simpleconfigurator/bundles.info
org.eclipse.swt.graphics.Resource.reportNonDisposed=true
org.eclipse.swt.internal.carbon.smallFonts=
org.eclipse.swt.internal.deviceZoom=200
org.osgi.framework.executionenvironment=OSGi/Minimum-1.0, OSGi/Minimum-1.1, OSGi/Minimum-1.2, JavaSE/compact1-1.8, JavaSE/compact2-1.8, JavaSE/compact3-1.8, JRE-1.1, J2SE-1.2, J2SE-1.3, J2SE-1.4, J2SE-1.5, JavaSE-1.6, JavaSE-1.7, JavaSE-1.8, JavaSE-9, JavaSE-10, JavaSE-11, JavaSE-12, JavaSE-13, JavaSE-14, JavaSE-15, JavaSE-16, JavaSE-17, JavaSE-18, JavaSE-19, JavaSE-20
org.osgi.framework.language=en
org.osgi.framework.os.name=MacOSX
org.osgi.framework.os.version=14.0.0
org.osgi.framework.processor=aarch64
org.osgi.framework.storage=/Applications/ide-latest-released/Eclipse.app/Contents/Eclipse/configuration
org.osgi.framework.system.capabilities=osgi.ee; osgi.ee="OSGi/Minimum"; version:List<Version>="1.0, 1.1, 1.2", osgi.ee; osgi.ee="JRE"; version:List<Version>="1.0, 1.1", osgi.ee; osgi.ee="JavaSE"; version:List<Version>="1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0",osgi.ee; osgi.ee="JavaSE/compact1"; version:List<Version>="1.8, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0",osgi.ee; osgi.ee="JavaSE/compact2"; version:List<Version>="1.8, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0",osgi.ee; osgi.ee="JavaSE/compact3"; version:List<Version>="1.8, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0"
org.osgi.framework.system.packages=com.sun.jarsigner, com.sun.java.accessibility.util, com.sun.jdi, com.sun.jdi.connect, com.sun.jdi.connect.spi, com.sun.jdi.event, com.sun.jdi.request, com.sun.management, com.sun.net.httpserver, com.sun.net.httpserver.spi, com.sun.nio.file, com.sun.nio.sctp, com.sun.security.auth, com.sun.security.auth.callback, com.sun.security.auth.login, com.sun.security.auth.module, com.sun.security.jgss, com.sun.source.doctree, com.sun.source.tree, com.sun.source.util, com.sun.tools.attach, com.sun.tools.attach.spi, com.sun.tools.javac, com.sun.tools.jconsole, java.applet, java.awt, java.awt.color, java.awt.datatransfer, java.awt.desktop, java.awt.dnd, java.awt.event, java.awt.font, java.awt.geom, java.awt.im, java.awt.im.spi, java.awt.image, java.awt.image.renderable, java.awt.print, java.beans, java.beans.beancontext, java.io, java.lang, java.lang.annotation, java.lang.constant, java.lang.foreign, java.lang.instrument, java.lang.invoke, java.lang.management, java.lang.module, java.lang.ref, java.lang.reflect, java.lang.runtime, java.math, java.net, java.net.http, java.net.spi, java.nio, java.nio.channels, java.nio.channels.spi, java.nio.charset, java.nio.charset.spi, java.nio.file, java.nio.file.attribute, java.nio.file.spi, java.rmi, java.rmi.dgc, java.rmi.registry, java.rmi.server, java.security, java.security.cert, java.security.interfaces, java.security.spec, java.sql, java.text, java.text.spi, java.time, java.time.chrono, java.time.format, java.time.temporal, java.time.zone, java.util, java.util.concurrent, java.util.concurrent.atomic, java.util.concurrent.locks, java.util.function, java.util.jar, java.util.logging, java.util.prefs, java.util.random, java.util.regex, java.util.spi, java.util.stream, java.util.zip, javax.accessibility, javax.annotation.processing, javax.crypto, javax.crypto.interfaces, javax.crypto.spec, javax.imageio, javax.imageio.event, javax.imageio.metadata, javax.imageio.plugins.bmp, javax.imageio.plugins.jpeg, javax.imageio.plugins.tiff, javax.imageio.spi, javax.imageio.stream, javax.lang.model, javax.lang.model.element, javax.lang.model.type, javax.lang.model.util, javax.management, javax.management.loading, javax.management.modelmbean, javax.management.monitor, javax.management.openmbean, javax.management.relation, javax.management.remote, javax.management.remote.rmi, javax.management.timer, javax.naming, javax.naming.directory, javax.naming.event, javax.naming.ldap, javax.naming.ldap.spi, javax.naming.spi, javax.net, javax.net.ssl, javax.print, javax.print.attribute, javax.print.attribute.standard, javax.print.event, javax.rmi.ssl, javax.script, javax.security.auth, javax.security.auth.callback, javax.security.auth.kerberos, javax.security.auth.login, javax.security.auth.spi, javax.security.auth.x500, javax.security.cert, javax.security.sasl, javax.smartcardio, javax.sound.midi, javax.sound.midi.spi, javax.sound.sampled, javax.sound.sampled.spi, javax.sql, javax.sql.rowset, javax.sql.rowset.serial, javax.sql.rowset.spi, javax.swing, javax.swing.border, javax.swing.colorchooser, javax.swing.event, javax.swing.filechooser, javax.swing.plaf, javax.swing.plaf.basic, javax.swing.plaf.metal, javax.swing.plaf.multi, javax.swing.plaf.nimbus, javax.swing.plaf.synth, javax.swing.table, javax.swing.text, javax.swing.text.html, javax.swing.text.html.parser, javax.swing.text.rtf, javax.swing.tree, javax.swing.undo, javax.tools, javax.transaction.xa, javax.xml, javax.xml.catalog, javax.xml.crypto, javax.xml.crypto.dom, javax.xml.crypto.dsig, javax.xml.crypto.dsig.dom, javax.xml.crypto.dsig.keyinfo, javax.xml.crypto.dsig.spec, javax.xml.datatype, javax.xml.namespace, javax.xml.parsers, javax.xml.stream, javax.xml.stream.events, javax.xml.stream.util, javax.xml.transform, javax.xml.transform.dom, javax.xml.transform.sax, javax.xml.transform.stax, javax.xml.transform.stream, javax.xml.validation, javax.xml.xpath, jdk.dynalink, jdk.dynalink.beans, jdk.dynalink.linker, jdk.dynalink.linker.support, jdk.dynalink.support, jdk.javadoc.doclet, jdk.jfr, jdk.jfr.consumer, jdk.jshell, jdk.jshell.execution, jdk.jshell.spi, jdk.jshell.tool, jdk.management.jfr, jdk.net, jdk.nio, jdk.nio.mapmode, jdk.security.jarsigner, jdk.swing.interop, netscape.javascript, org.ietf.jgss, org.w3c.dom, org.w3c.dom.bootstrap, org.w3c.dom.css, org.w3c.dom.events, org.w3c.dom.html, org.w3c.dom.ls, org.w3c.dom.ranges, org.w3c.dom.stylesheets, org.w3c.dom.traversal, org.w3c.dom.views, org.w3c.dom.xpath, org.xml.sax, org.xml.sax.ext, org.xml.sax.helpers, sun.misc, sun.reflect
org.osgi.framework.uuid=646a833b-e696-4f41-860b-dee8b4e3fa4b
org.osgi.framework.vendor=Eclipse
org.osgi.framework.version=1.10.0
org.osgi.supports.framework.extension=true
org.osgi.supports.framework.fragment=true
org.osgi.supports.framework.requirebundle=true
org.slf4j.simpleLogger.defaultLogLevel=off
os.arch=aarch64
os.name=Mac OS X
os.version=14.0
osgi.arch=aarch64
osgi.bundles=reference:file:org.eclipse.osgi.compatibility.state_1.2.800.v20221116-1440.jar,reference:file:org.eclipse.equinox.simpleconfigurator_1.4.300.v20230630-1506.jar@1:start
osgi.bundles.defaultStartLevel=4
osgi.compatibility.bootdelegation=true
osgi.compatibility.bootdelegation.default=true
osgi.configuration.area=file:/Applications/ide-latest-released/Eclipse.app/Contents/Eclipse/configuration/
osgi.configuration.cascaded=false
osgi.dataAreaRequiresExplicitInit=true
osgi.framework=file:/Users/vadymyusanenko/.p2/pool/plugins/org.eclipse.osgi_3.18.500.v20230801-1826.jar
osgi.framework.extensions=reference:file:org.eclipse.osgi.compatibility.state_1.2.800.v20221116-1440.jar
osgi.framework.shape=jar
osgi.framework.useSystemProperties=true
osgi.frameworkClassPath=., file:/Users/vadymyusanenko/.p2/pool/plugins/org.eclipse.osgi.compatibility.state_1.2.800.v20221116-1440.jar
osgi.install.area=file:/Applications/ide-latest-released/Eclipse.app/Contents/Eclipse/
osgi.instance.area=file:/Users/vadymyusanenko/workspace/
osgi.instance.area.default=file:/Users/vadymyusanenko/Documents/workspace/
osgi.logfile=/Users/vadymyusanenko/workspace/.metadata/.log
osgi.nl=en_UA
osgi.os=macosx
osgi.requiredJavaVersion=17
osgi.splashLocation=/Users/vadymyusanenko/.p2/pool/plugins/org.eclipse.platform_4.29.0.v20230903-1000/splash.png
osgi.splashPath=file:/Users/vadymyusanenko/.p2/pool/plugins/org.eclipse.platform_4.29.0.v20230903-1000
osgi.syspath=/Users/vadymyusanenko/.p2/pool/plugins
osgi.tracefile=/Users/vadymyusanenko/workspace/.metadata/trace.log
osgi.ws=cocoa
path.separator=:
socksNonProxyHosts=local|*.local|169.254/16|*.169.254/16
stderr.encoding=UTF-8
stdout.encoding=UTF-8
sun.arch.data.model=64
sun.boot.library.path=/Users/vadymyusanenko/.p2/pool/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.macosx.aarch64_20.0.2.v20230801-2057/jre/lib
sun.cpu.endian=little
sun.io.unicode.encoding=UnicodeBig
sun.java2d.d3d=false
sun.jnu.encoding=UTF-8
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
user.country=UA
user.dir=/Applications/ide-latest-released/Eclipse.app/Contents/MacOS
user.home=/Users/vadymyusanenko
user.language=en
user.name=vadymyusanenko
user.timezone=Europe/Kiev

**Comment by Phillipus** [comment] 2023-10-06 18:42
This is a duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/772

**Comment by vadym-yusanenko** [comment] 2023-10-06 18:46
> @vadym-yusanenko Would you mind if I closed this issue so we can keep it in one place at #772?

Sure, if it is already registered - the less clutter the better. Go for it! Thanks for pointing to original bug.

**Comment by Phillipus** [comment] 2023-10-06 18:47
OK, please refer to #772 as the root cause of this issue.

**Closed by Phillipus** 2023-10-06 18:47 UTC
