### ISSUE TITLE
Menus does not show on macOS Ventura

### ISSUE THREAD

**Issue by turesheim** [eclipse-platform/eclipse.platform.swt#256] opened 2022-07-13 07:15 UTC
Having tested Eclipse on macOS Ventura beta (22A5295i) using an M1 based computer. I found that everything appears to be in order, except that menus do not pop up. This includes right clicking on any element in an editor or in a view along with clicking on main items in the menu bar. Pressing shortcuts to open menus, i.e. ⌥⌘N in order to produce the new file menu – does not yield a result either.

**To Reproduce**

Install Eclipse 2022-06 on macOS Ventura. Try to open any menu.

**Expected behavior**

Menus should appear

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [ ] Linux
- - [X] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)

* macOS Ventura beta (22A5295i)
* Eclipse 2022-06
* AArch64
* JustJ JRE 17.0.3 (built-in)

**Workaround (or) Additional context**

While this is tested on a beta-version of macOS I don't think this problem will go away by itself.

**Comment by turesheim** [comment] 2022-07-13 07:36
I just discovered that if Eclipse is put in full screen mode, context menus (right click) do pop up. Menus activated using a keyboard shortcut also pop up as they should. However menus from the main menu bar do not.

**Comment by Phillipus** [comment] 2022-07-13 09:36
It would be interesting to see if this also happens with the Intel macOS version, either running on an Intel Mac or on a Silicon machine under Rosetta2 (and with x86_64 Java).

**Comment by lshanmug** [comment] 2022-07-13 11:24
Is the menubar or menu items disabled, something like https://bugs.eclipse.org/bugs/show_bug.cgi?id=520176? Can you please share a screenshot?

**Comment by turesheim** [comment] 2022-07-13 12:13
No. The menu bar is visible, but menu items does not show up. See attached screenshot. I suspect this bug is easy to reproduce, e.g. using snippet-29 so I'm having a go at that.

<img width="1440" alt="Skjermbilde 2022-07-13 kl  14 07 43" src="https://user-images.githubusercontent.com/337454/178730772-97ac7f2b-5797-4ab5-84fc-873fbff198b5.png">
.

**Comment by turesheim** [comment] 2022-07-13 18:27
I can confirm that [Snippet29](https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet29.java) reproduces the issue of items missing from the main menu bar. [Snippet238](https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet238.java) demonstrates how the menu appears when the `Shell` is in full screen mode, and how the menu does _not_ appear in windowed mode.

**Comment by Phillipus** [comment] 2022-07-14 08:26
This has also been reported here:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=580322

An interesting comment there is that "Eclipse 2022.03 works just fine". @turesheim Can you confirm that?

**Comment by turesheim** [comment] 2022-07-14 10:11
Yes, I can confirm that "Eclipse 2022.03" works just fine and does not have the issues reported here.

**Comment by lshanmug** [comment] 2022-07-14 11:30
We didn't have too many SWT Mac changes for 2022.06. I'm not sure, could it be caused by https://bugs.eclipse.org/bugs/show_bug.cgi?id=578171 ?

**Comment by Phillipus** [comment] 2022-07-14 12:45
I'm unable to install Ventura beta at the moment to bisect this.

@turesheim Is it possible you could install SWT source and binaries in Eclipse 4.23 host and test your snippets? If so, you could perhaps revert the changes in https://github.com/eclipse-platform/eclipse.platform.swt/commit/0794f8be6e871ceb8248f32b5f71c2f80c1dcc5e and test that?

**Comment by Phillipus** [comment] 2022-07-15 14:18
> We didn't have too many SWT Mac changes for 2022.06. I'm not sure, could it be caused by https://bugs.eclipse.org/bugs/show_bug.cgi?id=578171 ?

@lshanmug The answer is yes. I installed Ventura and commented out line 906 in `Display` class:

```
configureSystemOption ("NSMenuWindowManagerWindowShouldSetVisible", true);
```

And menu items work again. This line also stops combo boxes from displaying their contents as well.

CC @SyntevoAlex

**Comment by SyntevoAlex** [comment] 2022-07-15 14:37
Sigh, with every new macOS version they introduce new trouble

**Comment by Phillipus** [comment] 2022-07-15 15:04
@SyntevoAlex I tested your snippet `Bug578171_macOS_JvmCrash_ShowMenuWindow` and it does still crash on Ventura if that line in `Display` is commented out.

Also, SmartGit 21.2.3 is not showing main and context menu items in Ventura..

> Sigh, with every new macOS version they introduce new trouble

Tell me about it... 😢

**Comment by Phillipus** [comment] 2022-07-15 15:32
> Also, SmartGit 21.2.3 is not showing main and context menu items in Ventura..

Downloaded SmartGit 21.2.2 and that one is OK on Ventura. 😥

**Comment by Phillipus** [comment] 2022-07-15 15:57
Setting `NSMenuWindowManagerWindowShouldSetVisible` to `false` on Ventura makes no difference - menus are still missing.

**Comment by Phillipus** [comment] 2022-07-15 17:23
> I'll try to get macOS 13 installed 

@SyntevoAlex Be careful, you won't get the option to install Ventura on another Volume. See https://mrmacintosh.com/macos-ventura-13-full-installer-database-download-directly-from-apple/

**Comment by SyntevoAlex** [comment] 2022-07-20 02:11
Thanks for all the testing!
So far I didn't succeed with installing macOS 13.
I'll try to make a different patch at the end of this week, hopefully it will work better.
If you can't wait until then, just revert the patch.

**Comment by Phillipus** [comment] 2022-07-20 06:43
Better to wait for a different patch. macOS 13 is not released yet.

BTW - maOS 12.5 will be released soon (it's RC atm), I'm keeping an eye on that when it's final in case they backport the change into that one as well...

**Comment by turesheim** [comment] 2022-07-26 17:22
@SyntevoAlex @Phillipus  I also tested with snippet [Bug578171_macOS_JvmCrash_ShowMenuWindow](https://github.com/eclipse-platform/eclipse.platform.swt/blob/975011388a62584b52141fff2fa5c3d16ff4ec33/tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Bug578171_macOS_JvmCrash_ShowMenuWindow.java) and it does not crash on Ventura with the proposed pull request #274. The `Shell` will pop up as expected though.

**Comment by Phillipus** [comment] 2022-07-26 17:33
Bug578171_macOS_JvmCrash_ShowMenuWindow.java crashes for me on Ventura.

**Comment by Phillipus** [comment] 2022-07-26 17:46
BTW, @SyntevoAlex , SmartGit has also other problems under Ventura - tables and trees are not refreshing when contents change.

**Comment by SyntevoAlex** [comment] 2022-07-26 21:03
I'm still trying to get macOS 13 beta installed, and it doesn't want to be installed :(
@Phillipus could you please post your `hs_err_pid.log` file for a crash you're getting with my snippet on macOS 13?

**Comment by Phillipus** [comment] 2022-07-26 21:10
> could you please post your hs_err_pid.log file for a crash you're getting with my snippet on macOS 13?

To be clear, the crash only happens if this line is commented out, or not executed as in PR #274:

```configureSystemOption ("NSMenuWindowManagerWindowShouldSetVisible", true);```

[hs_err_pid768.log](https://github.com/eclipse-platform/eclipse.platform.swt/files/9193359/hs_err_pid768.log)

**Comment by Phillipus** [comment] 2022-07-26 21:12
> I'm still trying to get macOS 13 beta installed, and it doesn't want to be installed :(

What is the problem? Did you get a full installer as suggested in https://github.com/eclipse-platform/eclipse.platform.swt/issues/256#issuecomment-1185749133?

**Comment by SyntevoAlex** [comment] 2022-07-26 21:18
Yes, full installer. It seems that my hardware is not compatible. I would rather not discuss installing macOS here.

The crash log you posted matches the crash logs from macOS 12.

Which exact beta version do you have? Run `sw_vers` commandline command.

**Comment by Phillipus** [comment] 2022-07-26 21:22
> Which exact beta version do you have? Run sw_vers commandline command.

Version: 13.0
Build: 22A5295i

**Comment by SyntevoAlex** [comment] 2022-07-26 21:25
OK, so the very latest beta update. So I think that @turesheim did some mistake when testing.

**Comment by turesheim** [comment] 2022-07-27 10:31
> > Which exact beta version do you have? Run sw_vers commandline command.
> 
> Version: 13.0 Build: 22A5295i

@Phillipus I'm running the same version. See my initial description.


> OK, so the very latest beta update. So I think that @turesheim did some mistake when testing.

@SyntevoAlex Yes, I missed that the internal JRE was not used. 

I did another round using different runtime versions and sure enough, I am able to reproduce the crash when using the internal _JustJ JRE 17.0.3_. 

It is not reproducible when using the default Java on this system, _OpenJDK Runtime Environment Homebrew (build 11.0.15+0)_. 

I then installed another build, _OpenJDK Runtime Environment Homebrew (build 17.0.4+0)_, and are able reproduce the crash. Not that it should matter – but both the Homebrew runtime builds are Temurin based, just like JustJ.

It would seem that the crash behavior is related to runtimes later than 11.

**Comment by Phillipus** [comment] 2022-07-27 10:35
> It would seem that the crash behavior is related to runtimes later than 11.

No, it's crashing on 11. This is my JDK:

OpenJDK Runtime Environment Zulu11.56+19-CA (11.0.15+10) (build 11.0.15+10-LTS)

**Comment by turesheim** [comment] 2022-07-27 16:28
>>It would seem that the crash behavior is related to runtimes later than 11.
>No, it's crashing on 11. This is my JDK:
>
>OpenJDK Runtime Environment Zulu11.56+19-CA (11.0.15+10) (build 11.0.15+10-LTS)

I can confirm that it indeed does crash with _OpenJDK Runtime Environment Zulu11.58+15-CA (build 11.0.16+8-LTS_ - I'm still unable to reproduce with the Temurin JRE 11 build I mentioned though. Would you mind trying that too @Phillipus?

**Comment by Phillipus** [comment] 2022-07-27 16:40
Crashing the same with Temurin:

`OpenJDK Runtime Environment Temurin-11.0.15+10 (11.0.15+10) (build 11.0.15+10)`

**Comment by Phillipus** [comment] 2022-07-27 16:50
> That said. We are discussing two different issues here. Maybe we should create a new one for the crash and keep this for the missing menus?

Well, the simple fix for this bug is to remove this line in `Display`:

```
configureSystemOption ("NSMenuWindowManagerWindowShouldSetVisible", true);
```

But then this means that in the use case of @SyntevoAlex some users will experience a crash.

Some things to consider:

- Is this change in Ventura beta permanent or actually a new bug/regression? (i.e `NSMenuWindowManagerWindowShouldSetVisible` causing menus not to work)
- Is there another way to stop the crash so that `NSMenuWindowManagerWindowShouldSetVisible` can be removed?
- Can the crash be avoided by not allowing the situation to arise in the first place?

**Comment by Phillipus** [comment] 2022-07-27 18:19
macOS Ventura Beta 4 (22A5311f) was released today.

The situation with menus not showing and the menu crash if `NSMenuWindowManagerWindowShouldSetVisible` is removed remains the same.

**Comment by SyntevoAlex** [comment] 2022-07-27 22:41
I reworked the patch to use a different workaround.
Could you please test? I couldn't install macOS 13, and only tested on my macOS 12.

**Comment by SyntevoAlex** [comment] 2022-07-27 22:42
> SmartGit has also other problems under Ventura - tables and trees are not refreshing when contents change.

Alas, I can't fix it because I can't install macOS 13.

**Comment by Phillipus** [comment] 2022-07-28 09:20
> Could you please test https://github.com/eclipse-platform/eclipse.platform.swt/pull/277 ?

Menus are back and the test snippet doesn't crash. So, this is a 👍

**Closed** 2022-08-09 04:38 UTC
Labels: macOS
