### ISSUE TITLE
Bogus missing @since tag

### ISSUE THREAD

**Issue by basilevs** [eclipse-platform/eclipse.platform.swt#995] opened 2024-01-22 15:58 UTC
Compiling latest version of SWT, following error (and many similar) appear in Problem View:

```
Missing @since tag on org.eclipse.swt.widgets.Widget	Widget.java	/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets	line 54	@since tag problem
```
API Tools errors pollute workspace and obfuscate real problems.

**To Reproduce**
- [Deploy development environment](https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#creating-an-eclipse-development-environment)
- Wait for a release to happen
- Try to pull all Git repositories
- Refresh target platform
- Refresh API baseline

**Expected behavior**
No compilation errors on a clean master branch, if working copy matches the state of Github

**Screenshots**
<img width="1345" alt="Screenshot 2024-01-22 at 19 53 29" src="https://github.com/eclipse-platform/eclipse.platform.swt/assets/650857/3b5fc00f-6e60-4a0b-905a-bd64cd75c786">

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [x] All OS
- - [ ] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)

3. JRE/JDK version
 OpenJDK 17

**Version since**
Happens on each release of SWT (with SimRel)

**Workaround (or) Additional context**
Redeploy development environment from scratch after every release

**Comment by iloveeclipse** [comment] 2024-01-22 16:03
That is what I have since years... See https://bugs.eclipse.org/bugs/show_bug.cgi?id=532282.

The issue should actually be reported in https://github.com/eclipse-pde/eclipse.pde/issues but good to know that I'm not alone...

**Comment by merks** [comment] 2024-01-22 16:04
It’s annoying but hard to reproduce.  Often I just delete the baseline in the preferences.

**Comment by merks** [comment] 2024-01-22 16:11
Clean build and restart. Repeat. Sometimes works. Delete errors works until you change something.

**Comment by deepika-u** [comment] 2024-01-25 06:44
Yesterday my workspace had no errors and now today i did a rebase. Got 2 prs pulled 1000 and 999. Then did update .classpath of both swt and swt examples. Did a project clean and still seeing all these below errors -> 
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/46807064/707786df-c4ae-4d02-9bd8-4972255b93e9)

Am i missing something?

**Comment by deepika-u** [comment] 2024-01-25 08:27
Also updated baseline to 4.30, now seeing below
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/46807064/a76523b5-b8c4-46bb-9929-ca9d6dbc66f6)

Am i still missing something?

**Comment by iloveeclipse** [comment] 2024-01-25 08:29
> Am i still missing something?

Yes. A bugfix in PDE API tooling which reports wrong errors for SWT.

**Comment by iloveeclipse** [comment] 2024-01-25 08:35
I've created https://github.com/eclipse-pde/eclipse.pde/issues/1073.

I would keep this issue open, so SWT contributors could find it and see they are not alone...

**Comment by iloveeclipse** [comment] 2024-01-31 08:31
Fixed via https://github.com/eclipse-pde/eclipse.pde/pull/1093

**Closed by iloveeclipse** 2024-01-31 08:31 UTC
Labels: bug

**Comment by basilevs** [comment] 2024-04-19 06:42
The story continues:
![Uploading Screenshot 2024-04-19 at 10.41.48.png…]()

**Comment by iloveeclipse** [comment] 2024-04-19 07:42
> The story continues:

But not on this ticket please. 
I can't reproduce on latest SDK build & latest master state. If it is reproducible for you using latest SDK build, please create bug **for PDE**.
