### ISSUE TITLE
Eclipse is not fully switching to "Dark Theme/Mode"

### ISSUE THREAD

**Issue by TulioTsuruda** [eclipse-platform/eclipse.platform.swt#1559] opened 2024-10-26 02:41 UTC
I'm having an issue with my Eclipse. I'm using Windows 11, but I was forced to reformat it recently due to my previous NVME failing.

After reinstalling Windows and installing all drivers and updates, I installed Eclipse and noticed that when I switch Eclipse to Dark Mode, the taskbar isn't in Dark Mode, nor is the initial workspace selection screen. See some images below:
![image](https://github.com/user-attachments/assets/ad88a6c6-513f-49e3-95ae-0db3a4387600)
![image](https://github.com/user-attachments/assets/a32d55b5-0b57-420e-baa7-2c1a267e65f9)
![image](https://github.com/user-attachments/assets/7f6f1e07-b4a8-4cdf-b082-5fbb038e9d23)

Given that, I thought it might be because I was using a Dark Theme that comes with DevStyle. After installing the plugin, I noticed that even though it darkened some areas, the issue still wasn't resolved.
![image](https://github.com/user-attachments/assets/2afaec5c-2996-4eb7-a21a-8354508b8945)

I’ve already installed JRE 23 and JDK 17, but the issue wasn’t resolved.

I saw that others have encountered this problem before, and it was supposed to be fixed in the 2020 version, but I’m using the 2024-09 version. I even tried following the steps from the link below:

[Dark mode in Eclipse changes the color of the drop down menu text making it unreadable. How do I fix this?](https://stackoverflow.com/questions/66161910/dark-mode-in-eclipse-changes-the-color-of-the-drop-down-menu-text-making-it-unre#:%7E:text=Under%20Eclipse%20Bar%20Menu%20Window,of%20the%20available%20%22Dark%22%20themes)

I switched back to Light Mode and then back to Dark, but it still didn’t solve the problem.

Note: When I’m using the DevStyle theme, I always get the error below, and I have to end the task in Task Manager because of it.

![image](https://github.com/user-attachments/assets/f08392a0-5d8c-4efa-a6c8-8a97ea60054c)

So... Am I forgetting something? Is there something else I need to update? I don’t know what else to do since before, I didn’t have to do anything— I just downloaded Eclipse and started using it.

The difference is that instead of using a new version, I brought over the one I had on my old machine, which was a ZIP version. Since I unfortunately lost that version, I had to reconfigure everything from scratch, and this time I decided to download the executable instead of using the ZIP version.

Note: I also tried using the ZIP version, and the error is still the same.

Note: I'm using Eclipse IDE for Java Developers

What I'm hoping to resolve is getting my Eclipse to fully switch to Dark Mode. From what I see, what’s happening for me is not normal behavior.

[Windows menus are styled in the dark theme](https://eclipse.dev/eclipse/news/4.17/platform.php#dark-win32-menu)

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)

3. JRE/JDK version 23/17
 
**Version since**
 Eclipse or SWT version since when the behavior is seen [e.g. 4.23]

**Workaround (or) Additional context**
Any known workarounds for the problem?

**Comment by sratz** [comment] 2024-10-26 09:54
This is a duplicate of #1546.
Dark mode API slightly changed in Windows 11 24H2.
It should be fixed with #1547.
You can try out with the latest integration build version of Eclipse from https://download.eclipse.org/eclipse/downloads/ or alternatively the fix will be part of Eclipse 2024-12.

**Closed by sratz** 2024-10-26 09:54 UTC

**Comment by kingthorin** [comment] 2024-11-24 02:05
> The Eclipse IDE 2024-12 release is scheduled for December 4, 2024
