### ISSUE TITLE
GC#drawIcon draws *.ico(for some icons) with black background on Windows 10

### ISSUE THREAD

**Issue by tmssngr** [eclipse-platform/eclipse.platform.swt#185] opened 2022-06-01 08:10 UTC
**Describe the bug**
Please run the attached snippet on Windows 10 (default Windows mode: Dark, default app mode: light). It will get the icons for certain file types and render them. For some reason, the background of the images is rendered in black.
[ProgramImageTest.java.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/8812245/ProgramImageTest.java.txt)

**To Reproduce**
See above.

**Expected behavior**
The background should be transparent.

**Screenshots**
![Screenshot-Win10](https://user-images.githubusercontent.com/6029561/171358110-b3332cae-19fd-4ad1-846c-ab8b7305c156.png)

**Environment:**
Windows 10, Version 21H1 (OS Build 19043.1706)

**Comment by tmssngr** [comment] 2022-06-01 09:19
This is reproducible with the latest SWT built from source (v4952r11). With bisecting I've found out that commit 22797d3f _Revert "Revert "Bug 493455 - [win32] remove alpha and alphaData from Image""_ introduced this bug.

**Comment by niraj-modi** [comment] 2022-06-01 10:10
> This is reproducible with the latest SWT built from source (v4952r11). With bisecting I've found out that commit [22797d3](https://github.com/eclipse-platform/eclipse.platform.swt/commit/22797d3f9f09ca67bfd29c864f2aaf8eb452c75c) _Revert "Revert "Bug 493455 - [win32] remove alpha and alphaData from Image""_ introduced this bug.

@jonathan.meier@outlook.com
Please have a look.

**Comment by niraj-modi** [comment] 2022-06-01 11:42
I don't see this problem happening in Eclipse.

@SyntevoAlex @Phillipus 
Do you see this problem in any of you Eclipse based applications ?
We are just trying to understand how severe is this problem.

**Comment by Phillipus** [comment] 2022-06-01 11:43
I guess it's too late to fix this for 4.24? We were hoping to build our RCP app on 4.24, but with this regression I guess we'll have to postpone until 4.25 in September.

**Comment by niraj-modi** [comment] 2022-06-01 12:01
> I don't have those program icons on my system, so when I run the snippet the program icons I have render OK. @tmssngr Can we get an actual icon to test with? Also, is this Hi DPI?

Please share a screen grab on how the icon looks for you.

**Comment by Phillipus** [comment] 2022-06-01 12:18
> Please share a screen grab on how the icon looks for you.

![icons](https://user-images.githubusercontent.com/600504/171402700-e3e23fd0-e2ba-4c8c-a17b-f2baf15624a5.png)

**Comment by Phillipus** [comment] 2022-06-01 12:29
Found it.

I had to set Windows custom scaling to 200 and run the snippet with the argument `-Dswt.autoScale=200`

![icons2](https://user-images.githubusercontent.com/600504/171404510-bfed691c-ab5a-47ce-9263-6cccd84a7910.png)

**Comment by niraj-modi** [comment] 2022-06-01 12:46
Eclipse at HiDPI is working fine for External Program Icons:
![Eclipse_ExternalProgram_Icons](https://user-images.githubusercontent.com/92304759/171407552-852e425d-ef96-4b59-9211-62fd2ee0b182.png)

So problem seems specific to this test-snippet only.

**Comment by Phillipus** [comment] 2022-06-01 13:00
It seems to be only some Program icons that have this problem.

Try running this modified snippet:

<details>
<summary>Modified Snippet</summary>

```java
import java.util.List;
import java.util.*;

import org.eclipse.swt.*;
import org.eclipse.swt.graphics.*;
import org.eclipse.swt.program.*;
import org.eclipse.swt.widgets.*;

public class ProgramImageTest {

	public static void main(String[] args) {
		final Display display = new Display();

		final List<Image> images = createImages(display, "zip", "pdf", "png", "jpg", "msi", "txt", "theme");

		final Shell shell = new Shell(display);

		shell.addListener(SWT.Paint, event -> {
			int x = 0; int y = 0;
			for (Image image : images) {
				event.gc.drawImage(image, x, y);
				x += image.getImageData().width;
				x += 10;
				if(x > 400) {
				    x = 0;
				    y += 24;
				}
			}
		});

		shell.setSize(400, 300);
		shell.open();

		while (!shell.isDisposed()) {
			if (!display.readAndDispatch()) {
				display.sleep();
			}
		}

		for (Image image : images) {
			image.dispose();
		}

		display.dispose();
	}

	private static List<Image> createImages(Display display, String... extensions) {
		final List<Image> images = new ArrayList<>();
		
		for(Program p : Program.getPrograms()) {
		    final ImageData data = p.getImageData();
            if (data == null) {
                continue;
            }

            images.add(new Image(display, data));
        }
		
		return images;
	}
}
```
</details>

**Comment by Phillipus** [comment] 2022-06-01 13:30
Strange, now I am able to reproduce this with scaling at 100%:

![icons3](https://user-images.githubusercontent.com/600504/171416306-71948d37-c9c4-4c9d-96ee-751080859aa4.png)

**Comment by niraj-modi** [comment] 2022-06-01 13:49
> Strange, now I am able to reproduce this with scaling at 100%:
> 
> ![icons3](https://user-images.githubusercontent.com/600504/171416306-71948d37-c9c4-4c9d-96ee-751080859aa4.png)

Interestingly problem is seen only with second run onward irrespective of zoom.
Even got it working with 200% as well:
![Snippet_200Zoom](https://user-images.githubusercontent.com/92304759/171419541-09ca1cf4-900e-442c-af83-1d799864e0aa.png)

Revised steps to reproduce the issue with test-snippet:
1. Switch the Windows Display zoom 100% to 200%(or visa versa)
2. Run the test-snippet, it will works on either zoom.
3. Close it and relaunch, problem is seen.

**Comment by Phillipus** [comment] 2022-06-01 14:57
I tried to narrow it down to loading an icon from file, but couldn't reproduce it other than the icons returned from `Program.getImageData()`. Perhaps there is something in the way that ImageData is created there that was missed in https://bugs.eclipse.org/bugs/show_bug.cgi?id=493455

**Comment by niraj-modi** [comment] 2022-06-02 07:05
> As an experiment I changed line 366 of `org.eclipse.swt.program.Program` from:
> 
> `int flags = OS.SHGFI_ICON | OS.SHGFI_SMALLICON | OS.SHGFI_USEFILEATTRIBUTES;`
> 
> to:
> 
> `int flags = OS.SHGFI_SMALLICON | OS.SHGFI_USEFILEATTRIBUTES;`
> 
> And the icons are rendered OK.
> 
> Might be a clue?

With above suggested changes the transparent background issue is addressed but the size of icons is coming too small and also seems blurred:
![Possible_Fix](https://user-images.githubusercontent.com/92304759/171572689-986216b5-d13b-45bf-ad33-b830a26f561e.png)

**Comment by Phillipus** [comment] 2022-06-02 08:36
I don't think it's related to HiDPI. I'm seeing it on normal 100% scaling all the time now. See https://github.com/eclipse-platform/eclipse.platform.swt/issues/185#issuecomment-1143939862

**Comment by Phillipus** [comment] 2022-06-02 12:49
I've isolated the problem to *.ico files. Nothing to do with `Program.getImageData` or HiDPI.

Attached is a reproducible snippet and icon file.

Here's how it should look running on Eclipse 4.23:

![icon_4 23](https://user-images.githubusercontent.com/600504/171632626-ea635597-ff89-47a3-9bc0-4c6b8f63da2a.png)

Here's how it looks on Eclipse 4.24:

![icon_4 24](https://user-images.githubusercontent.com/600504/171632697-589ff855-840d-452f-8544-c98fc8f4e0d1.png)

[ImageTest.zip](https://github.com/eclipse-platform/eclipse.platform.swt/files/8823847/ImageTest.zip)

**Comment by Phillipus** [comment] 2022-06-02 14:23
>  changed the title [HiDPI] Program.getImageData returns images with black background on Windows 10 GC#drawIcon draws *.ico(for some icons) with black background on Windows 10

GC#drawImage

**Comment by jonathan-meier** [comment] 2022-06-02 20:34
The problem is here
https://github.com/eclipse-platform/eclipse.platform.swt/blob/6f2f07c0f6c2cb80ee1d072d669ce1c7d5d957a4/bundles/org.eclipse.swt/Eclipse%20SWT/win32/org/eclipse/swt/graphics/Image.java#L1800-L1803

In commit 22797d3 I changed this from
```
case 32:
	if (!(redMask == 0xFF00 && greenMask == 0xFF0000 && blueMask == 0xFF000000)) {
		newPalette = new PaletteData(0xFF00, 0xFF0000, 0xFF000000);
	}
	break;
```
enforcing that any alpha data for an image *must* be provided via the `ImageData.alphaData` field and any alpha data in the fourth channel of the `ImageData.data` field for 32-bit images is strictly ignored. I did this to align the `win32` implementation with the `gtk` implementation of `Image`, however, I forgot to consider the special case of icons (loaded from ICO files) that provide a 32-bit image and a mask.

For such icons, retrieving their `ImageData` via `Image.getImageData` (this is used inside `Program.getImageData`) does not populate the `ImageData.alphaData` field, even though the fourth channel of the image data contains valid alpha data and therefore, the alpha data is discarded when again creating an `Image` from this `ImageData`.

This becomes a problem for icons that do *not* use the color black for transparent pixels. Masked pixels colored in black become transparent, whereas masked pixels colored in any other color are XORed with their background color by GDI, which means that a masked pixel colored in white inverts its background color. This is exactly what happens in all examples provided above, where the white background is inverted to black by masked pixels colored in white. It happens only with a few icons, since most icons use the color black for transparent pixels.

Using the following method, you can color all masked pixels black to work around this issue:
```
private static void maskColor(ImageData imageData) {
	byte[] maskData = imageData.maskData;
	if (maskData == null || imageData.depth != 32) {
		return;
	}

	byte[] data = imageData.data;
	int stride = maskData.length / imageData.height;
	for (int i = 0, dp = 0, mbp = 0; i < imageData.height; i++, mbp += stride) {
		for (int j = 0, mp = mbp; j < imageData.width; mp++) {
			for (int b = 7; b >= 0 && j < imageData.width; b--, j++, dp++) {
				int mask = (maskData[mp] >> b) & 0x1;
				for (int c = 0; c < 3; c++, dp++) {
					data[dp] = (byte) (data[dp] * mask);
				}
			}
		}
	}
}
```

This still does not fix partially transparent pixels which are just drawn fully opaque when discarding the alpha channel, but this is much less visible and icons using partially transparent pixels are less common.

I will provide a PR with a fix for this issue as soon as possible. Thanks everyone for providing insights helping debug this issue :+1:

**Comment by Phillipus** [comment] 2022-06-16 09:43
> I will provide a PR with a fix for this issue as soon as possible. Thanks everyone for providing insights helping debug this issue

Hi, did you find some time to implement a PR? Happy to test it if required. 👍

**Comment by tmssngr** [comment] 2022-07-01 08:21
@jonathan-meier Unfortunately, your `maskColor` method doesn't resolve the problem for me (Windows 10).

**Comment by Phillipus** [comment] 2022-07-05 09:01
> This is reproducible with the latest SWT built from source (v4952r11). With bisecting I've found out that commit [22797d3](https://github.com/eclipse-platform/eclipse.platform.swt/commit/22797d3f9f09ca67bfd29c864f2aaf8eb452c75c) _Revert "Revert "Bug 493455 - [win32] remove alpha and alphaData from Image""_ introduced this bug.

@tmssngr Do you think if we reverted this, it would solve the regression?

**Comment by tmssngr** [comment] 2022-07-05 11:55
I've tried reverting e8916589140e7dcd1d0d8504998d631f1c0bd48f, 819a24e0a953caee4eaac384639ff4a958d9817f, def5c63081058881bcce98004349276f577bd32f and 22797d3f9f09ca67bfd29c864f2aaf8eb452c75c, but then it did not compile any more because of a missing `hDC` in `Image`. Because I'm not an expert in the internals, I've aborted my tests.

**Comment by tmssngr** [comment] 2022-07-07 08:14
I really would appreciate it if this obvious regression could be fixed soon.

**Comment by Phillipus** [comment] 2022-07-07 09:34
> I really would appreciate it if this obvious regression could be fixed soon.

@jonathan-meier Hi Jonathan, do you think it is possible to fix this regression?

**Comment by niraj-modi** [comment] 2022-07-07 12:51
> The problem is here
> 
> https://github.com/eclipse-platform/eclipse.platform.swt/blob/6f2f07c0f6c2cb80ee1d072d669ce1c7d5d957a4/bundles/org.eclipse.swt/Eclipse%20SWT/win32/org/eclipse/swt/graphics/Image.java#L1800-L1803
> 
> In commit [22797d3](https://github.com/eclipse-platform/eclipse.platform.swt/commit/22797d3f9f09ca67bfd29c864f2aaf8eb452c75c) I changed this from
> 
> ```
> case 32:
> 	if (!(redMask == 0xFF00 && greenMask == 0xFF0000 && blueMask == 0xFF000000)) {
> 		newPalette = new PaletteData(0xFF00, 0xFF0000, 0xFF000000);
> 	}
> 	break;
> ```
Based on above input, I have a working fix for this issue:
- Will share a PR for testing shortly.

**Comment by Phillipus** [comment] 2022-07-07 13:00
@niraj-modi Hi Niraj, thanks for taking a look at this. I tested your patch with the example case in https://github.com/eclipse-platform/eclipse.platform.swt/issues/185#issuecomment-1144825489 and I can confirm it seems to fix the problem.

**Closed** 2022-07-11 11:18 UTC
Labels: regression, Windows
