### ISSUE TITLE
The button reports a different colour to what is actually displayed

### ISSUE THREAD

**Issue by JVS94** [eclipse-platform/eclipse.platform.swt#619] opened 2023-04-07 09:45 UTC
**Environment:** Windows and macOS 

The `BackgroundMode` of `container` is `SWT.INHERIT_FORCE` :
```java
Shell shell = new Shell() ;
shell.setSize( 300, 100 ) ;
shell.setLayout( new FillLayout() ) ;

Composite container = new Composite( shell, SWT.NONE ) ;
container.setLayout( new GridLayout( 2, true ) ) ;
container.setBackgroundMode( SWT.INHERIT_FORCE ) ;
container.setBackground( new Color( 255, 0, 0 ) ) ;
System.out.println( "container : " + container.getBackgroundMode() ) ;
System.out.println( "container : " + container.getBackground() ) ;

Button button = new Button( container, SWT.NONE ) ;
button.setText( "button" ) ;
System.out.println( "button : " + button.getBackground() ) ;

Label label = new Label( container, SWT.NONE ) ;
label.setText( "label" ) ;
System.out.println( "label : " + label.getBackground() ) ;

shell.open() ;
```
```
container : 2
container : Color {255, 0, 0, 255}
button : Color {255, 0, 0, 255}
label : Color {255, 0, 0, 255}
```
![image](https://user-images.githubusercontent.com/44021373/230570291-d72d6be1-6156-479f-9025-1d395ee188ef.png)

The result is confusing. The `Background` of `button` is `{255, 0, 0, 255}`, but the screen capture shows it isn't actually red.

**Comment by iloveeclipse** [comment] 2023-04-07 09:58
Please don't create identical bug reports!
Closing as duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/618.

**Closed by iloveeclipse** 2023-04-07 09:58 UTC
