### ISSUE TITLE
Browser widgets using Edge flicker when resized causing flashes

### ISSUE THREAD

**Issue by kwinter108** [eclipse-platform/eclipse.platform.swt#1122] opened 2024-03-18 15:20 UTC
# Describe the bug
Browser widgets using the Edge browser flicker when resized. When included in a RCP Part and resized, the flicker can cause rapid flashing between a black background and the content displayed in the browser. The flashes created can exceed the threshold defined in [WCAG 2.1 - SC 2.3](https://www.w3.org/WAI/WCAG21/Understanding/seizures-and-physical-reactions) and may trigger seizures in individuals who have photosensitive seizure disorders.

# To Reproduce
## Option 1
1. Start the Eclipse application "_Runtime Workspace_" with this VM-Arg: `-Dorg.eclipse.swt.browser.DefaultType=Edge`
2. Resize the _JavaDoc_ view

### Video
**WARNING: This video may potentially trigger seizures for people with photosensitive epilepsy. Viewer discretion is advised.**
[flickering_javadoc_view_using_edge_as_browser](https://github.com/user-attachments/assets/9e7b42bc-d4ed-4ca6-b7c8-d0d1a8c10843)

## Option 2
1. Create a RCP application (the 'Create sample content' option can be used to speed up the remaining steps)
4. Create 2 Part Stacks in the same Part Sash Container.
5. Create a Part in each Part Stack and associate them to classes. One of the parts must contain a Browser widget using the SWT.EDGE style. Set the browser to any valid URL. The other Part can contain any widget as it only exists to allow the parts to be resized within the window.
6. Launch the application using the .product file.
7. Resize the application window.
8. Use the mouse to drag the boarder between the Parts to cause the Browser to resize.

### Video
**WARNING: This video may potentially trigger seizures for people with photosensitive epilepsy. Viewer discretion is advised.**
[Recording of issue](https://github.com/eclipse-platform/eclipse.platform.swt/assets/25162503/e71193f3-078a-4c16-a673-88c9306d481b)

# Expected behavior
Browser widgets using the Edge browser should resize smoothly without causing flickering.

# Environment
1. Select the platform(s) on which the behavior is seen:
*I have only been able to test this issue on a Windows machine. Given the nature of this issue, it is likely that it will occur in Linux and macOS as well*
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

9. Additional OS info (e.g. OS version, Linux Desktop, etc)
+ Windows 10 Pro version 22H2
+ Windows 11 Pro version 23H2

10. JRE/JDK version
JDK 11 and JDK 17

# Version since
I have seen this occur in 4.21 and 4.31. It likely has been occurring since the introduction of Edge support in 4.19.

# Workaround (or) Additional context
The only workaround I have been able to identify for this issue is to use a listener for the SWT.Resize event to hide the browser temporarily while resizing.

**Comment by amartya4256** [comment] 2024-11-05 16:39
I had a look into it and I have found out the root cause of this problem. It is not a problem of Edge browser. It only happens when the browser is opened in a SashLayout. In windows, on mouse move, SashLayout executes a callback where it tries to call layout synchronously because there's some problem with Async requestLayout call. Thus, to do so the underlying implementation has to disable the redraw before calling the sync layout and after the layout call, enable it again and then call an update on the composite. The composite in this case is the one that contains CTabFolder. When the composite disables redraw, Webview disappears; I reckon it is because of the default behavior of WebView. Once the layout call has finished, the redraw is reenabled - which leads to reappearance of the webview - which leads to the current flickering behaviour. 
Getting rid of the disabling of redraw fixes the flickering of the webview of course but since, we see a shaky behaviour in the minimize and maximize buttons as we move (That's the reason we disable and enable the redraw while calling the layout). Even using requestLayout (async) leads to the same shaky behaviour.

However, one thing which must we taken into account is that this flicker issue happens only in SashLayour because of the problem mentioned above. It is also valid for Snippet Explorer; if you open the preview of a snippet with a big image and resize the partition, you can reproduce the same effect.

If you open the browser and minimize it and open it from the sidebar (not by maximizing), you can try resizing the browser and it would not flicker, since it is not using a SashLayout there. 

Now, for SashLayout I have tried several ways to somehow getrid of this disabling of redrawing, but the best behaviour I could achieve was with no flicker in the browser but the shaky CTabFolder max min buttons on resizing the folders. However, the same shaky behaviour can also be found by default for the example I mentioned above with the browser if you open it without maximizing its CTabFolder from the sidebar; if you resize it, you'll see no flicker, but the minmax buttons will shake as you do it.

I also found a bug which was reported long ago around it - https://bugs.eclipse.org/bugs/show_bug.cgi?id=558392

**Comment by fedejeanne** [comment] 2024-12-06 10:04
Fixed by #1588

**Closed by fedejeanne** 2024-12-06 10:04 UTC
Labels: Windows, edge
