### ISSUE TITLE
Drag and drop of tabs not working in Linux

### ISSUE THREAD

**Issue by manoda0** [eclipse-platform/eclipse.platform.swt#1248] opened 2024-05-22 19:31 UTC
If you try to drag any tab (Project Explorer, Console, Errors, Outline...) in Eclipse and drop somewhere else to change the perspective layout, the tabs don't move correctly. Nothing happens most of the time although sometimes drag and drop works, intermittently.

The bug happens in **Eclipse IDE for Enterprise Java and Web Developers** versions **2022-09 (4.25)** and **2024-03 (4.31)**.

Drag and drop of tabs work correctly in Eclipse IDE for Enterprise Java and Web Developers version 2022-06 (4.24).

It seems something changed in version 4.25 broke compatibility with Linux.

The bug happens in **Ubuntu Desktop 22.04.4 LTS** and in **Debian 12.5** Operating Systems, both with the default Gnome GUI.

Drag and drop of tabs work correctly in Windows 10 Pro.

**Comment by iloveeclipse** [comment] 2024-05-22 20:38
Duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/589

**Closed by iloveeclipse** 2024-05-22 20:38 UTC
Labels: bug, Linux/GTK, Wayland
