### ISSUE TITLE
Both Eclipse 2022-06 and 2022-12 often hanging forever on startup

### ISSUE THREAD

**Issue by davidmichaelkarr** [eclipse-platform/eclipse.platform.swt#539] opened 2023-01-26 14:33 UTC
For the last few weeks, I've been struggling with Eclipse 2022-12 consistently hanging forever on startup, and 2022-06 often doing the same thing, but seemingly not as often.  Yesterday afternoon, I started 2022-12 and it got into the hung state, so I left it alone until later in the evening, and it was still hung.  I took a threaddump at that point, killed the process, and then started 2022-06. It appeared to hang also.  I left it alone until this morning, and it was still hung.  I took a threaddump at that point and killed the process.  I'm getting to the point where I can't get anything done with this.
[threaddump.202206.txt](https://github.com/eclipse-platform/eclipse.platform.debug/files/10510211/threaddump.202206.txt)
[threaddump.202212.txt](https://github.com/eclipse-platform/eclipse.platform.debug/files/10510212/threaddump.202212.txt)

**Comment by jonahgraham** [comment] 2023-01-26 14:40
@davidmichaelkarr it looks like Eclipse is hanging in the Windows native code that calculates exactly how to layout text.

As far as I can tell the issue is in a console view. Can you provide any insights about which console views may be involved so I can try to reproduce this?

```

"main" #1 prio=6 os_prio=0 cpu=16956234.38ms elapsed=30861.56s tid=0x00000148ee5f1a20 nid=30224 runnable  [0x0000003a16b1d000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.swt.internal.win32.OS.ScriptPlace(Native Method)
        at org.eclipse.swt.graphics.TextLayout.shape(TextLayout.java:3760)
        at org.eclipse.swt.graphics.TextLayout.computeRuns(TextLayout.java:405)
        at org.eclipse.swt.graphics.TextLayout.getBounds(TextLayout.java:1657)
        at org.eclipse.swt.custom.StyledTextRenderer.calculate(StyledTextRenderer.java:299)
```

**Comment by jonahgraham** [comment] 2023-01-26 14:42
If possible, can you take a few stack dumps back to back? I don't think you need to leave it overnight, a few minutes of a hang is sufficient.

Other useful information is which version of Windows are you using?

**Comment by davidmichaelkarr** [comment] 2023-01-26 15:36
Microsoft Windows 11 Enterprise, Version 10.0.22000 (Service Pack: 0.0)

This is 2022-06.  I believe I have the lsp console enabled in this version. I use Maven, so occasionally the Maven console is running. I often run springboot applications, and I have a console for that.  I'm not sure what others would be there. Is it possible to determine the available consoles from the file system?  I can't very well determine what's there right now.

[threaddump.202206.5.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/10510759/threaddump.202206.5.txt)
[threaddump.202206.4.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/10510761/threaddump.202206.4.txt)
[threaddump.202206.3.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/10510762/threaddump.202206.3.txt)
[threaddump.202206.2.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/10510764/threaddump.202206.2.txt)
[threaddump.202206.1.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/10510765/threaddump.202206.1.txt)
[threaddump.202206.7.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/10510766/threaddump.202206.7.txt)
[threaddump.202206.6.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/10510767/threaddump.202206.6.txt)

**Comment by davidmichaelkarr** [comment] 2023-01-26 19:00
Ok, well, I made the change to that file and restarted, but it's still hanging.
[threaddump.202206.afteransichange.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/10512513/threaddump.202206.afteransichange.txt)

**Comment by davidmichaelkarr** [comment] 2023-01-26 19:35
Hmm, after another try, I see that it is not hanging yet. If anything, there is a  race condition that results in it not happening all the time.  I made the same change in 2022-12 workspace, and I've tried restarting a couple of times now, and it hasn't hung yet.  I'm willing to try other variations if it helps you narrow this down.

**Comment by jonahgraham** [comment] 2023-01-26 19:47
Do any of the consoles have any text in them? That may help.

![image](https://user-images.githubusercontent.com/679236/214934994-84c54af3-bb8f-4fdf-9093-5cf7a0b0bd67.png)

---

> Note that I also had this line in that file:
> `org.eclipse.ui.console.P_CONSOLE_WORD_WRAP=true`

Work wrapping the console can slow it down so dramatically that it looks hung. But as you left it overnight it seems unlikely that was the sole problem. I recommend turning off work wrap if you have any performance problems in the console.

**Comment by davidmichaelkarr** [comment] 2023-01-26 20:54
Before this point I have never noticed any performance problems in the console, and I set word wrap in the console every time I install Eclipse.

In my running 2022-12 instance, which is currently NOT hung, I have three consoles:
* org.eclipse.lsp4e
* Emacs+ Console
* A SpringBoot application console

The contents of the second one is easy, as it gets the same content every time I start Eclipse:
```
Kbd Macro convert-setter-to-fluent-setter loaded
Kbd Macro println loaded
```

The lsp4e console as of right now has 90k lines in it, and I see that some of them are very long lines. I suppose that word wrap might have to do a bit of work there, but note that my Eclipse is currently NOT hung.

As of right now, the spring-boot application console has quite a few lines in it, but again, Eclipse is currently NOT hung, and this console would never have any content at startup.  The lsp4e console OFTEN does have content at startup.

**Comment by davidmichaelkarr** [comment] 2023-01-26 23:07
I had another hang of the 2022-12 instance, so I decided to try turning off wordwrap. The next attempt didn't hang. That doesn't mean it fixed the problem, just a data point.

**Comment by jonahgraham** [comment] 2023-01-27 01:02
That sounds frustrating and I appreciate your persistence in trying to solve the problem.

90k lines in the console is also quite a lot. You could try limiting the console output if you don't need it all. But similar to word wrap, I can understand some performance degredations and some hangs, but not an overnight amount. That still sounds like something more significant. 

Are you able to attach the output from LSP4E console, that seems like the most likely culprit as it is there when you start up? If you are concerned about updating an arbitrary log, you can email it to me jonah at kichwacoders dot com and I can experiment with it and hopefully create a reproducer.

![image](https://user-images.githubusercontent.com/679236/214983487-fed5a099-c4a4-4253-9d04-bd6c3c3b5110.png)

**Comment by davidmichaelkarr** [comment] 2023-01-29 00:57
Sorry I haven't responded in a while. I've gone in a slightly different direction, simply disabling the lsp4e console, and also setting a console limit of 200000.  I've tried restarts several times since I did that, and I haven't seen a deadlock yet.

**Comment by jonahgraham** [comment] 2023-01-29 01:54
Thank you David for reporting back. While I obviously want to reproduce the problem, for now I am delighted to hear that we seem to have a solution that allows you to proceed.

I am going to close this issue now as there isn't anything actionable anymore. Happy to reopen it if more details come up.

In addition, I have started a discussion on https://github.com/eclipse/lsp4e/discussions/419 to spread the word about the hangs you have seen to see if other LSP4E users or devs have run across this.

**Closed by jonahgraham** 2023-01-29 01:54 UTC
Labels: Windows
