### ISSUE TITLE
[GTK][Wayland] Double clicking sometimes results in an unfinished drag&drop

### ISSUE THREAD

**Issue by tmssngr** [eclipse-platform/eclipse.platform.swt#247] opened 2022-07-08 10:23 UTC
**Describe the bug**
When quickly clicking onto a Tree or Table control on Linux, sometimes the dragStart event is sent, but no belonging dragFinished event. I'm using Ubuntu 21.04 in a VirtualBox VM.

**To Reproduce**
Please launch the attached snippet and quickly double click randomly the table items. Events are logged to the terminal. Usually, a

drag start

line is immediately followed by a

drag finished

line, but sometimes it isn't. This can cause problems in applications that expect the dragFinished event to be called after a drag.

**Expected behavior**
Make the dragFinished event always be sent after a dragStart event.

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [x] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
Stock Ubuntu 21.10 (-> Gnome desktop).

[Test.java.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/9071267/Test.java.txt)

**Comment by Phillipus** [comment] 2022-07-08 10:46
Missing bracket in test code. Should be:

<details>
<summary>Test Snippet</summary>

```java
import org.eclipse.swt.*;
import org.eclipse.swt.dnd.*;
import org.eclipse.swt.layout.*;
import org.eclipse.swt.widgets.*;

public class Test {
	public static void main(String[] args) {
		final Display display = new Display();

		final Shell shell = new Shell(display);
		shell.setLayout(new FillLayout());

		final Table table = new Table(shell, SWT.BORDER);
		final TableColumn column = new TableColumn(table, SWT.LEFT);
		column.setText("Column");
		column.setWidth(200);

		for (int i = 0; i < 10; i++) {
			final TableItem item = new TableItem(table, SWT.LEFT);
			item.setText("Item " + i);
		}

		table.addListener(SWT.Selection, event -> System.out.println("selection changed " + event.time));
		table.addListener(SWT.MouseDown, event -> {
			if (event.doit && event.count == 2 && event.button == 1 && event.stateMask == 0) {
				System.out.println("lmb double clicked " + event.time);
			}
		});

		final DragSource dragSource = new DragSource(table, DND.DROP_MOVE);
		dragSource.setTransfer(TextTransfer.getInstance());
		dragSource.addDragListener(new DragSourceAdapter() {
			@Override
			public void dragStart(DragSourceEvent event) {
				System.out.println("drag start");
			}

			@Override
			public void dragFinished(DragSourceEvent event) {
				System.out.println("drag finish");
			}
		});

		shell.setSize(400, 300);
		shell.open();

		while (!shell.isDisposed()) {
			if (!display.readAndDispatch()) {
				display.sleep();
			}
		}

		display.dispose();
	}
}
```
</details>

**Comment by SyntevoAlex** [comment] 2022-07-08 11:41
Reproducible on Ubuntu 21.04 also. Try clicking mouse quickly while moving it over TreeItem slowly.

**Comment by Phillipus** [comment] 2022-07-08 12:12
> yes, Wayland

OK, I was using X11. I think there are a few problems with mouse events under Wayland. 

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=572615

**Comment by SyntevoAlex** [comment] 2022-07-08 21:42
Indeed the problem is not reproducible with X11 (via `export GDK_BACKEND=x11`)

**Comment by SyntevoAlex** [comment] 2022-07-09 02:29
Here's a patch: https://github.com/eclipse-platform/eclipse.platform.swt/pull/248

**Comment by SyntevoAlex** [comment] 2022-07-09 02:33
I added logging in SWT and GTK and when bug occurs, the output is:
```
GTK:gtk_drag_begin_internal
SWT:DragBegin
GTK:data_source_target
GTK:data_source_action
GTK:data_source_target
GTK:data_source_cancelled
SWT:DragEnd
GTK:gtk_drag_begin_internal
SWT:DragBegin
```

That is, SWT starts a new drag&drop right after the previous ended. I suspect that SWT does this when mouse is already released (but maybe SWT still doesn't know because it didn't process all events). I didn't investigate further because it's hard and the patch already fixes the problem.

**Comment by SyntevoAlex** [comment] 2022-07-09 02:59
A better summary of this bug: when double-clicking, sometimes SWT starts a drag&drop operation, which becomes stuck (never receives `DragEnd`). This may happen even if a single double click is done after starting the program. There's no need to click a lot, it's simply an easier way to reproduce.

**Closed** 2022-08-09 16:31 UTC
Labels: bug, Linux/GTK, Wayland
