### ISSUE TITLE
NPE error when creating a GLCanvas on MacOS

### ISSUE THREAD

**Issue by sea-lmarchal** [eclipse-platform/eclipse.platform.swt#378] opened 2022-09-08 17:35 UTC
**Describe the bug**
As soon as a a Glcanvas is created on OSX BigSur (or after) a NPE is thrown and the canvas cannot be used. see https://bugs.eclipse.org/bugs/show_bug.cgi?id=570649 for a full report
```
java.lang.NullPointerException
 	at org.eclipse.swt.widgets.Widget.drawRect(Widget.java:763)
 	at org.eclipse.swt.widgets.Canvas.drawRect(Canvas.java:170)
 	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6037)
 	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
 	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Display.java:5317)
 	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5710)
 	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
 	at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(NSApplication.java:92)
 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3833)
 	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
 	at org.eclipse.jface.window.Window.open(Window.java:799)
 	at com.google.gapid.Main$UI.show(Main.java:136)
 	at com.google.gapid.Main.main(Main.java:80)
```
**To Reproduce**
```
public class SWTSnippet {

	public static void main( String[] args ) {
		Display display = new Display();
		Shell shell = new Shell( display );
		shell.setLayout( new FillLayout() );
		shell.setBounds( 100, 100, 400, 400 );

		// This does not work.
		Canvas canvas = new GLCanvas( shell, SWT.NONE, new GLData() );

		// This works.
		// Canvas canvas = new Canvas( shell, SWT.NONE );

		canvas.addListener( SWT.Paint, event -> handlePaint( event ) );
		canvas.addListener( SWT.MouseMove, event -> canvas.redraw() );

		shell.open();
		while ( !shell.isDisposed() ) {
			if ( !display.readAndDispatch() ) {
				display.sleep();
			}
		}
		display.dispose();
	}

	private static void handlePaint( Event event ) {
		int xBegin = 10 + (int) ( Math.random() * 10 );
		int xEnd = 390 - (int) ( Math.random() * 10 );
		int yBegin = 10 + (int) ( Math.random() * 10 );
		int yEnd = 350 - (int) ( Math.random() * 10 );

		event.gc.setLineWidth( 3 );
		event.gc.setForeground( Display.getDefault().getSystemColor( SWT.COLOR_RED ) );
		event.gc.drawLine( xBegin, yBegin, xEnd, yEnd );
	}
}
```

**Expected behavior**
A working GlCanvas

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ X] macOS BigSur or after

2. Additional OS info (e.g. OS version, Linux Desktop, etc)

3. JRE/JDK version
 
**Version since**
 Since Eclipse 4.18+

**Workaround (or) Additional context**
None

**Comment by lshanmug** [comment] 2022-09-15 05:12
duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/237

**Closed by lshanmug** 2022-09-15 05:12 UTC
