### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.ole.win32.OleFrame.onFocusOut(org.eclipse.swt.widgets.Event)" because "this.this$0.frame" is null

### ISSUE THREAD

**Issue by MLausberg** [eclipse-platform/eclipse.platform.swt#1157] opened 2024-04-02 10:59 UTC
**Describe the bug**
We have created a modal dialog with a Browser Widget inside.
When opening the modal dialog and updating the browserWidget content a NullPointer is thrown.
Not always, but sometimes.
We assume a focus timing issue.

**To Reproduce**
No small application exists you can use to reproduce the problem easily.
Even in our heavy application the problem appers randomly.

**Expected behavior**
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.ole.win32.OleFrame.onFocusOut(org.eclipse.swt.widgets.Event)" because "this.this$0.frame" is null
	at org.eclipse.swt.ole.win32.OleClientSite$1.handleEvent(OleClientSite.java:148) ~[org.eclipse.swt.win32.win32.x86_64_3.124.0.v20230523-1044.jar:?]
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89) ~[org.eclipse.swt.win32.win32.x86_64_3.124.0.v20230523-1044.jar:?]
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274) ~[org.eclipse.swt.win32.win32.x86_64_3.124.0.v20230523-1044.jar:?]
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066) ~[org.eclipse.swt.win32.win32.x86_64_3.124.0.v20230523-1044.jar:?]
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090) ~[org.eclipse.swt.win32.win32.x86_64_3.124.0.v20230523-1044.jar:?]
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075) ~[org.eclipse.swt.win32.win32.x86_64_3.124.0.v20230523-1044.jar:?]
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778) ~[org.eclipse.swt.win32.win32.x86_64_3.124.0.v20230523-1044.jar:?]
	at org.eclipse.swt.ole.win32.OleFrame.lambda$1(OleFrame.java:161) ~[org.eclipse.swt.win32.win32.x86_64_3.124.0.v20230523-1044.jar:?]
	at org.eclipse.swt.widgets.Display.runTimer(Display.java:4170) ~[org.eclipse.swt.win32.win32.x86_64_3.124.0.v20230523-1044.jar:?]
	at org.eclipse.swt.widgets.Display.messageProc(Display.java:3290) ~[org.eclipse.swt.win32.win32.x86_64_3.124.0.v20230523-1044.jar:?]
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method) ~[org.eclipse.swt.win32.win32.x86_64_3.124.0.v20230523-1044.jar:?]
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3658) ~[org.eclipse.swt.win32.win32.x86_64_3.124.0.v20230523-1044.jar:?]
	at de.dsa.rcp.plugins.screen.swtwidgets.browser.win.SWTBrowserDisplayThread.run(SWTBrowserDisplayThread.java:99) [de.dsa.rcp.plugins.screen.swtwidgets_5.0.18.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [x] Windows

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
Windows 11

3. JRE/JDK version
 openjdk 17.0.8 2023-07-18
OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7)
OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode, sharing)

**Version since**
org.eclipse.swt.win32.win32.x86_64_3.124.0.v20230523-1044.jar
org.eclipse.swt_3.124.0.v20230523-1044.jar
Eclipse 2023-06 (4.28)

**Workaround (or) Additional context**

**Comment by jukzi** [comment] 2024-04-16 12:09
OleClientSite.frame is only nulled in onDispose() which also calls removeListener(FocusOut) so i don't know how this could happen. You will need to provide a reproducer or fix. for me it would be ok to ignore FocusOut Event if the widget is already disposed.

**Comment by jukzi** [comment] 2024-05-13 12:55
closing as not reproducable - since no reproducer was given.

**Closed by jukzi** 2024-05-13 12:55 UTC
Labels: needinfo
