### ISSUE TITLE
NPE Clicking on Next Button

### ISSUE THREAD

**Issue by davidaca** [eclipse-platform/eclipse.platform.swt#313] opened 2022-08-12 16:05 UTC
**Describe the bug**
PDE New Target Definition Wizard cannot continue by clicking Next button. A stack trace is printed

`!ENTRY org.eclipse.ui 4 0 2022-08-12 10:19:40.336
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.calculateVisibleRegion(Control.java:780)
	at org.eclipse.swt.widgets.Control.getVisibleRegion(Control.java:2063)
	at org.eclipse.swt.widgets.Control.isObscured(Control.java:2344)
	at org.eclipse.swt.widgets.Scrollable.scrollClipViewToPoint(Scrollable.java:348)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6112)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSScrollView.setDocumentView(NSScrollView.java:74)
	at org.eclipse.swt.widgets.Scrollable.setZOrder(Scrollable.java:397)
	at org.eclipse.swt.widgets.Control.createWidget(Control.java:1031)
	at org.eclipse.swt.widgets.Scrollable.createWidget(Scrollable.java:170)
	at org.eclipse.swt.widgets.Text.createWidget(Text.java:588)
	at org.eclipse.swt.widgets.Control.<init>(Control.java:119)
	at org.eclipse.swt.widgets.Scrollable.<init>(Scrollable.java:73)
	at org.eclipse.swt.widgets.Text.<init>(Text.java:133)
	at org.eclipse.pde.internal.ui.SWTFactory.createText(SWTFactory.java:378)
	at org.eclipse.pde.internal.ui.wizards.target.TargetDefinitionContentPage.createArgumentsGroup(TargetDefinitionContentPage.java:484)
	at org.eclipse.pde.internal.ui.wizards.target.TargetDefinitionContentPage.createControl(TargetDefinitionContentPage.java:177)
	at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:176)
....`
(Full stack trace attached)

**To Reproduce**
Preferences>Plug-in development>Target Platform>Add
Press Next button 

**Expected behavior**
Continue through wizard pages.

**Screenshots**

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [] All OS
- - [ ] Windows
- - [ ] Linux
- - [X ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
MacOS version 11.6.8 (20G730)

3. JRE/JDK version
Java(TM) 2 Runtime Environment, Standard Edition (IBM build 1.8.0_321-b06 08_Feb_2022_11_58 Mac OS X x64(SR7 FP5)) 

**Version since**
 Eclipse or SWT version since when the behavior is seen [e.g. 4.23]
Seen in Photon. To be checket other versions
org.eclipse.swt.cocoa.macosx.x86_64 3.106.3.v20210826-1500

MacOS version 11.6.8 (20G730)

**Workaround (or) Additional context**
Any known workarounds for the problem?
[NPE.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/9324726/NPE.txt)

**Comment by Phillipus** [comment] 2022-08-12 17:50
I tried to reproduce this but it worked as expected.

macOS 12.5
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
Eclipse 4.23

**Comment by lshanmug** [comment] 2022-08-17 07:37
Are you using multiple monitors? The issue looks same as in https://bugs.eclipse.org/bugs/show_bug.cgi?id=559198

**Comment by elsazac** [comment] 2023-04-14 11:45
@davidaca 
Are you still facing this problem? if yes, please share the in detail recreate steps. 

I have tried it on below environment and it is working as expected.

Eclipse SDK
Version: 2023-06 (4.28)
Build id: I20230405-1800
OS: Mac OS X, v.13.2.1, aarch64 / cocoa
Java vendor: Oracle Corporation
Java runtime version: 19.0.1+10-21
Java version: 19.0.1

**Comment by Phillipus** [comment] 2023-04-14 11:48
This requires non-Retina monitor to reproduce and is fixed in https://github.com/eclipse-platform/eclipse.platform.swt/pull/622

**Comment by davidaca** [comment] 2023-04-17 14:50
> @davidaca
> Are you still facing this problem?

Having:
_macos 12.6.3
eclipse 2023-03 (4.27.0)_

The problem went away.

**Comment by deepika-u** [comment] 2023-04-18 06:32
@davidaca : can we close this issue then?

**Comment by SyntevoAlex** [comment] 2023-04-18 15:36
Closed as duplicate of #472

**Closed by SyntevoAlex** 2023-04-18 15:36 UTC
Labels: macOS
