### ISSUE TITLE
[Cocoa] Possible NPE in Combo.mouseDown

### ISSUE THREAD

**Issue by tmssngr** [eclipse-platform/eclipse.platform.swt#317] opened 2022-08-16 11:45 UTC
**Describe the bug**
For our SWT-based application we've received a couple of NPEs in Combo.mouseDown, like this one:
```
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Combo.mouseDown(SourceFile:1158)
	at org.eclipse.swt.widgets.Display.windowProc(SourceFile:6149)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper
	at org.eclipse.swt.widgets.Widget.callSuper(SourceFile:235)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(SourceFile:2150)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(SourceFile:2487)
	at org.eclipse.swt.widgets.Display.windowProc(SourceFile:6273)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper
	at org.eclipse.swt.widgets.Widget.callSuper(SourceFile:235)
	at org.eclipse.swt.widgets.Widget.mouseDownSuper(SourceFile:1146)
	at org.eclipse.swt.widgets.Widget.mouseDown(SourceFile:1138)
	at org.eclipse.swt.widgets.Control.mouseDown(SourceFile:2631)
	at org.eclipse.swt.widgets.Combo.mouseDown(SourceFile:1156)
	at org.eclipse.swt.widgets.Display.windowProc(SourceFile:6149)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper
	at org.eclipse.swt.widgets.Widget.callSuper(SourceFile:235)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(SourceFile:2150)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(SourceFile:2487)
	at org.eclipse.swt.widgets.Display.windowProc(SourceFile:6273)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper
	at org.eclipse.swt.widgets.Display.applicationSendEvent(SourceFile:5517)
	at org.eclipse.swt.widgets.Display.applicationProc(SourceFile:5660)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(SourceFile:117)
	at org.eclipse.swt.widgets.Display.readAndDispatch(SourceFile:3909)
```

**To Reproduce**
Unfortunately, this bug is not reliably reproducible.

**Expected behavior**
No NPE.

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [ ] Linux
- - [x] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
Has been reported against macOS 10.15-12.4.

4. JRE/JDK version
Java 11
 
**Version since**
Unknown.

**Workaround (or) Additional context**
```
@Override
void mouseDown(long id, long sel, long theEvent) {
	// If this is a combo box with an editor field and the control is disposed
	// while the view's cell editor is open we crash while tearing down the
	// popup window. Fix is to retain the view before letting Cocoa track
	// the mouse events.

	display.sendPreExternalEventDispatchEvent();
	// 'view' will be cleared if disposed during the mouseDown so cache it.
	NSView viewCopy = view;
	viewCopy.retain();
	super.mouseDown(id, sel, theEvent);
	viewCopy.release();
	display.sendPostExternalEventDispatchEvent();
}
```
In the last line the NPE occurs, so it looks like `display` gets nulled. Maybe it needs to be cached, too?

**Comment by Phillipus** [comment] 2022-08-16 16:47
Is this related to or the same as https://github.com/eclipse-platform/eclipse.platform.swt/issues/254 ?

**Comment by tmssngr** [comment] 2022-08-19 16:31
Err, yes. ;)

**Comment by lshanmug** [comment] 2022-08-22 11:44
Duplicate of #254

**Closed by lshanmug** 2022-08-22 11:44 UTC
