### ISSUE TITLE
Ubuntu 23.04 - strange artifacts in certain resolutions

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.swt#859] opened 2023-11-05 21:47 UTC
If I use Ubuntu 23.04 with 200% resolution, I see back artifacts in the product, MANIFEST.MF and plugin.xml editor. 

![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/139910/3e975439-4156-4c58-95a1-a2dcc00fdae2)

**Comment by Phillipus** [comment] 2023-11-06 10:40
See https://github.com/eclipse-platform/eclipse.platform.swt/issues/577

**Comment by iloveeclipse** [comment] 2023-11-06 10:42
Closing as duplicate of #577

**Closed by iloveeclipse** 2023-11-06 10:42 UTC
