### ISSUE TITLE
JDT tooltips are blank when MS Edge browser is used in Eclipse using "-Dorg.eclipse.swt.browser.DefaultType=edge"

### ISSUE THREAD

**Issue by jjohnstn** [eclipse-platform/eclipse.platform.swt#398] opened 2022-09-20 18:48 UTC
Copying from: https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/248

If running Eclipse with -Dorg.eclipse.swt.browser.DefaultType=edge under e.g. Windows 11 or 10, the tooltips shown by JDT in for example Java editors are empty. This is probably due to SWT issues with the Browser component being MS Edge and not MS Internet Explorer (or MS Edge in MSIE compatibility mode on Windows 11).
Eclipse 2022-09 RC1 under Windows 11

Below, you will see the tooltip on a boolean variable:

![image](https://user-images.githubusercontent.com/1216877/191340044-007bc565-ba5b-4b8b-8035-a47f46443396.png)

If -Dorg.eclipse.swt.browser.DefaultType=edge is not specified, it works, both in Windows 10 and 11:

![image](https://user-images.githubusercontent.com/1216877/191340200-8ec89fb3-401f-4d16-98f7-6a1502eb4836.png)

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [X] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)

3. JRE/JDK version
 
**Workaround (or) Additional context**
If -Dorg.eclipse.swt.browser.DefaultType=edge is not specified, it works, both in Windows 10 and 11:

**Comment by Phillipus** [comment] 2022-09-20 19:26
Same as https://github.com/eclipse-platform/eclipse.platform.swt/issues/212

**Comment by akurtakov** [comment] 2022-09-21 05:04
Duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/212

**Closed by akurtakov** 2022-09-21 05:04 UTC
