### ISSUE TITLE
Control.setFocus must not bring the application to front if it is in the background

### ISSUE THREAD

**Issue by tmssngr** [eclipse-platform/eclipse.platform.swt#450] opened 2022-10-24 14:53 UTC
Please run the attached snippet. It opens 3 shells, simulates some loading and then wants to set the focused control for each of the shells. Unfortunately, (sometimes) it brings the shell to front, even if it was in the background. If I would want to bring a shell to front, I would invoke `shell.setActive()`, but I just want to change the focuses control inside a shell.
```java
import org.eclipse.swt.*;
import org.eclipse.swt.layout.*;
import org.eclipse.swt.widgets.*;

public class FocusToFrontTest {

	public static void main(String[] args) {
		final FocusToFrontTest test = new FocusToFrontTest();
		test.openShell();
		test.openShell();
		test.openShell();
		test.show();
	}

	private final Display display = new Display();

	private int count;

	private FocusToFrontTest() {
	}

	private void openShell() {
		count++;
		final Shell shell = new Shell(display);
		final int number = count;
		shell.setText("Window " + number);
		shell.setLayout(new FillLayout());
		shell.addListener(SWT.Dispose, event -> count--);
		shell.addListener(SWT.Activate, event -> System.out.println("Activated " + number));
		shell.setSize(400, 300);

		final Text text1 = new Text(shell, SWT.BORDER | SWT.MULTI);
		text1.setText("Loading...");

		final Text text2 = new Text(shell, SWT.BORDER | SWT.MULTI | SWT.WRAP);

		shell.open();

		display.timerExec(1_000 * number, () -> {
			if (shell.isDisposed()) {
				return;
			}

			text1.setText("");
			text2.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
			text2.setFocus();
		});
	}

	private void show() {
		while (count > 0) {
			if (!display.readAndDispatch()) {
				display.sleep();
			}
		}

		display.dispose();
	}
}
```
This ticket is related to https://bugs.eclipse.org/bugs/show_bug.cgi?id=578929, but instead of adding new API it should fix the existing one.

**Comment by tmssngr** [comment] 2022-12-14 07:16
Hi Alexander, do you need further input from me to accept this fix?

**Comment by akurtakov** [comment] 2022-12-14 07:26
Honestly, it just got lost in the pile of other issues/prs.

**Comment by akurtakov** [comment] 2022-12-14 09:21
Should be fixed via https://github.com/eclipse-platform/eclipse.platform.swt/pull/451

**Comment by iloveeclipse** [comment] 2022-12-15 07:14
Caused regression, see https://github.com/eclipse-platform/eclipse.platform.swt/issues/502

**Comment by iloveeclipse** [comment] 2022-12-15 10:24
I see a bigger regression now, that would break different clients.

Ctrl+Shift+T + start typing doesn't work anymore: the opened dialog does not have focus set in the text field.
The problem is that dialog is created & focus is set **before** the shell has been opened / focused!

![image](https://user-images.githubusercontent.com/964108/207835062-114ed6d4-a2d0-41f7-afc9-8da076920445.png)

We should revert this commit until we have a plan how to fix that.

**Comment by sratz** [comment] 2022-12-15 10:32
We also have almost a hundred of assorted unit tests of our product failing after this change.

I suppose it would be better to add a 2nd API method (or parameterize `setFocus(...)`) to give consumers a choice, but avoid changing existing behavior, as originally proposed in the bugzilla.

**Comment by iloveeclipse** [comment] 2022-12-15 10:36
I also see it in Egit "create branch" dialog etc - in all places where a new shell is opened and something should have a focus...

**Comment by mickaelistria** [comment] 2022-12-15 10:36
> I suppose it would be better to add a 2nd API method (or parameterize setFocus(...)) to give consumers a choice, but avoid changing existing behavior, as originally proposed in the bugzilla.

I don't think so; giving focus in 1 app is a different from pushing an application to front.
And I suspect your tests wouldn't be failing even if setFocus() behaves in a way that doesn't bring control to front; they're more likely failing for the reason described by @iloveeclipse which seems to be a bug in the current proposed implementation; but when the implementation doesn't have such bugs, there wouldn't be such issue and no such need for a different `setFocus()` method.

@iloveeclipse thanks for identifying that case. Do you think it can be easily turned into a test case in SWT code base? If so, it would be nice to add it now to not take risk of regressing the same way again with other attempts at fixing this issue.

**Comment by iloveeclipse** [comment] 2022-12-15 10:42
I believe automated test **could** work, but not sure because handling focus is the most sensible part of UI testing. I'm pretty sure it will be unstable and/or very platform specific.

Beside this, I've prepared PR https://github.com/eclipse-platform/eclipse.platform.swt/pull/503 with revert.
As said, if @tmssngr doesn't find a solution, I would like to merge it this evening, so next SDK build is usable again.

**Comment by iloveeclipse** [comment] 2022-12-15 10:57
Other manifestation of same issue: switching from one shell by clicking on a link in the first shell to another opened shell isn't working anymore, because the "other one" isn't forcing the focus anymore.

Open editor in IDE, show revision information, hover over left ruler to see some commit: shows a shell with a diff -> show revision information -> opens an editor in background and does NOT hides the shell / shows the editor as it was before.

**Comment by tmssngr** [comment] 2022-12-15 19:12
On what operating system you reproduce the problems?

**Comment by iloveeclipse** [comment] 2022-12-15 19:37
RHEL 7.9  GTK 3.22.
No, no time. Please try to create shell from other shell and focus widget in the new one before opening. That would not work because new shell is not active yet.

**Comment by tmssngr** [comment] 2022-12-16 09:25
I've tried to reproduce with this snippet, but it works fine on latest Manjaro/Gnome:
```
import org.eclipse.swt.*;
import org.eclipse.swt.layout.*;
import org.eclipse.swt.widgets.*;

public class DialogFocusTest {

	public static void main(String[] args) {
		final Display display = new Display();

		final Shell mainShell = new Shell(display);
		mainShell.setLayout(new GridLayout(1, false));

		final Button button = new Button(mainShell, SWT.PUSH);
		button.setText("Open Dialog");
		button.addListener(SWT.Selection, event -> openDialog(mainShell));
		button.setLayoutData(new GridData(GridData.BEGINNING, GridData.BEGINNING, false, false));

		mainShell.setSize(500, 400);
		mainShell.open();

		while (!mainShell.isDisposed()) {
			if (!display.readAndDispatch()) {
				display.sleep();
			}
		}

		display.dispose();
	}

	private static void openDialog(Shell parent) {
		final Shell shell = new Shell(parent, SWT.DIALOG_TRIM | SWT.PRIMARY_MODAL);
		shell.setLayout(new GridLayout(1, false));

		createText(shell, "First");
		createText(shell, "Second").setFocus();

		shell.setSize(500, 300);
		shell.open();
	}

	private static Control createText(Composite parent, String message) {
		final Text text = new Text(parent, SWT.SINGLE | SWT.BORDER);
		text.setMessage(message);
		text.setLayoutData(new GridData(GridData.FILL, GridData.BEGINNING, true, false));
		return text;
	}
}

```

**Comment by akurtakov** [comment] 2022-12-16 09:27
Do you run X11 or Wayland? Behavior on both differ significantly.

**Comment by iloveeclipse** [comment] 2022-12-16 09:33
Snippet works for me with the patch (on X11). So you have to dig into IDE code to find where the difference to the plain SWT is. 
May be the flags used to create shells.

**Comment by tmssngr** [comment] 2022-12-19 19:11
I'd appreciate it if someone could share a snippet that reproduces the problem with the undone patch (commit 7d28a780).

**Comment by tmssngr** [comment] 2023-01-18 10:00
Ping. I need a snippet to reproduce the problems with my pull request. Otherwise I can't fix it.

**Comment by iloveeclipse** [comment] 2023-01-18 16:25
> Ping. I need a snippet to reproduce the problems with my pull request. Otherwise I can't fix it.

Thomas, don't get me wrong, but you have to create that snippet by yourself.
Unfortunately my time is limited and I can't spend time on issues that are not relevant for me personally or my job.

Grab latest SDK. Debug that regression from Eclipse - use cases are plenty. Find out which JFace / IDE component is involved in all that mess. Try to reduce to plain SWT.

**Comment by merks** [comment] 2023-01-18 19:53
Setting up an IDE is completely automated.   Just drop this link on the installer or read the instructions for how to do that:

https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse-platform/eclipse.platform.releng.aggregator/master/oomph/PlatformSDKConfiguration.setup&show=true

**Comment by SyntevoAlex** [comment] 2023-01-24 17:33
Here's a summary of the topic, as I understand it:

1. `Control.forceFocus()` currently activates the parent `Shell` if it wasn't active.
2. This is undesired, because an application jumps on a user who was doing something else.
3. There was an attempt to suppress it, but this caused regressions.
4. The current patch tries to implement a new API, but every new API comes at a price of supporting it.

I understand that regressions fall into two major categories:
1. If focus is set in inactive Shell, focus shall be remembered and applied when Shell becomes active.
   Example: https://github.com/eclipse-platform/eclipse.platform.swt/issues/450#issuecomment-1352853224
   Example: https://github.com/eclipse-platform/eclipse.platform.swt/issues/450#issuecomment-1352867147
2. Sometimes an app may want to activate an already opened `Shell` by setting focus to its `Control`.
   Example (if I understand it correctly from description): https://github.com/eclipse-platform/eclipse.platform.swt/issues/450#issuecomment-1352891577

The first regression type should be easy enough to fix. For example, on Windows, I see `Decorations#savedFocus`, which seem to be a part of the idea to restore focus when `Shell` becomes active.

The second regression type is more interesting, and I see two potential solutions here:
1. Declare that it is the SWT user's responsibility to `Shell.forceActive()` when another `Shell` is to be activated.
   Yes, there will be some places in Eclipse etc to fix. But it will make code better because it will no longer rely on undocumented behavior (`Control.forceFocus()` documentation doesn't promise to activate `Shell`). Also, the code will more explicitly do what it wants.
2. Try to be compatible. I would say, "only activate Shell if currently active Shell belongs to the same app".

Summary: I don't think a new API is needed. Rather, old one should be fixed to not do things it never promised to do.

**Comment by SyntevoAlex** [comment] 2023-01-24 17:38
Also, I think that second regression type should be rare. It's sounds uncommon to have two Shells opened side by side, where a button/link/etc in one Shell activates the other Shell.

**Comment by tmssngr** [comment] 2023-01-25 06:59
Where can I find the sources for the Ctrl+Shift+T dialog to understand what exactly it does? Are there information how to debug Eclipse (here the Ctrl+Shift+T dialog)?

**Comment by merks** [comment] 2023-01-25 07:04
The plug-in spies are quite useful.  Shift-Alt-F1 for information about the control is focus and Shift-Al-F2 for information about a menu to toolbar item (the cursor changes and you can select the item).

![image](https://user-images.githubusercontent.com/208716/214500686-864201f4-3544-43dc-b8d9-d472b07a3249.png)

So it's org.eclipse.jdt.internal.ui.dialogs.OpenTypeSelectionDialog.

**Comment by tmssngr** [comment] 2023-01-25 14:02
@merks Thanks. Unfortunately, I don't know Eclipse good enough to know how to install that "Plug-in Selection Spy" (I've installed some "SWT Spy" but couldn't see find it any more), I also don't know where to find the sources for `org.eclipse.jdt.internal.ui.dialogs.OpenTypeSelectionDialog` (which repository to clone from https://github.com/orgs/eclipse-platform/repositories?) nor how to debug that. Sorry, I'm neither an Eclipse user nor an Eclipse developer, just an SWT user.

**Comment by merks** [comment] 2023-01-25 14:19
This automated setup produces a development environment with all the clones you need for everything in the Eclipse SDK, including everything from Equinox, PDE, JDT and Platform:

https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#create-an-eclipse-development-environment

It's great for the source *.java files for anything and the spies are already installed.  And you can launch a Runtime Workspace debug any of the changes you make any of the projects.

**Comment by tmssngr** [comment] 2023-01-26 08:29
Sorry, it looks like I'm too stupid to follow the steps at https://wiki.eclipse.org/Eclipse_Platform_SDK_Provisioning - the screenshots look different for me. At the end it only installs a normal Eclipse installation. I does not seem to download any Eclipse sources.

**Comment by merks** [comment] 2023-01-26 08:38
It sounds like you did not tell the installer to switch to advanced mode when you dropped the link on it.

if you drag this link:

https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse-platform/eclipse.platform.releng.aggregator/master/oomph/PlatformSDKConfiguration.setup&show=true

And drop it on the installer's title area, it should prompt you like this:

![image](https://user-images.githubusercontent.com/208716/214791445-8be6c3a0-477e-4ef9-90c4-6e54fd97c031.png)

**Comment by tmssngr** [comment] 2023-01-26 11:55
I understand now the problem with my patch better. With https://github.com/eclipse-platform/eclipse.platform.swt/issues/450#issuecomment-1354443395 it can be reproduced by not setting the focus to the second, but to the first `Text` control. I believe now that `restoreFocus()` inside `Shell.open()` relies on the activation of the new shell. It looks like I need to find a different kind of fix.

**Comment by tmssngr** [comment] 2023-02-09 10:23
Did any of you had time to look at my patch and try it with Eclipse?

**Comment by iloveeclipse** [comment] 2023-02-09 10:27
> Did any of you had time to look at my patch and try it with Eclipse?

Thomas, could you please ask that on PR itself? Which one is ready to review?

**Comment by tmssngr** [comment] 2023-02-11 08:56
I've did: https://github.com/syntevo/eclipse.platform.swt/commit/e260f3c6c808b4bc34306c798aaf3ba3d09025e2

**Comment by tmssngr** [comment] 2023-02-16 10:57
With this snippet a regression happened (no control received the focus) without the changes in `shell.open`:
```
import org.eclipse.swt.*;
import org.eclipse.swt.layout.*;
import org.eclipse.swt.widgets.*;

public class LinuxShellOpenTest {

	public static void main(String[] args) throws InterruptedException {
		Thread.sleep(1000);

		final Display display = new Display();
		display.timerExec(1000, new Runnable() {
			@Override
			public void run() {
				System.out.println("Focus " + display.getFocusControl());
				display.timerExec(1000, this);
			}
		});

		final Shell shell = new Shell(display);
		shell.setLayout(new FillLayout());
		final Composite composite = new Composite(shell, SWT.NO_RADIO_GROUP | SWT.NO_BACKGROUND);
		composite.setLayout(new FillLayout());
		final Canvas canvas = new Canvas(composite, SWT.NORMAL);
		canvas.addListener(SWT.KeyDown, event -> {
			System.out.println(event.character);
		});

		shell.setSize(400, 300);
		shell.open();

		while (!shell.isDisposed()) {
			if (!display.readAndDispatch()) {
				display.sleep();
			}
		}

		display.dispose();
	}
}
```
Here is a new fix: https://github.com/eclipse-platform/eclipse.platform.swt/pull/553

**Comment by syntevo** [comment] 2023-05-24 09:47
I would need help in setting up the two-shell-unit test. Is there some other unit test which does similar things?

**Comment by tmssngr** [comment] 2023-05-24 09:53
I would need help in creating such a two-shell-unit test. Is there some other which I can use or just add the normal snippet code into a `@Test` method?

**Comment by SyntevoAlex** [comment] 2023-05-24 21:10
Sorry, I didn't understand what exactly do you want help with.
Yes, it's more or less about moving snippet code under `@Test`, also adapting it to run automatically without user interactions.

**Comment by SyntevoAlex** [comment] 2023-05-31 20:12
Let's review regressions encountered when developing this patch.
I'm referencing to my summary in https://github.com/eclipse-platform/eclipse.platform.swt/issues/450#issuecomment-1402329573

> If focus is set in inactive Shell, focus shall be remembered and applied when Shell becomes active.

I understand that you fixed it?

> Sometimes an app may want to activate an already opened Shell by setting focus to its Control.

What did you decide about this one?

> Ctrl+Shift+T

Can you explain what did you change in your patch to solve that?
Is it currently covered by unit test?

**Comment by tmssngr** [comment] 2023-06-09 14:58
>> If focus is set in inactive Shell, focus shall be remembered and applied when Shell becomes active.
> I understand that you fixed it?

IMHO, this behavior already existed, so there was nothing to fix.

> Sometimes an app may want to activate an already opened Shell by setting focus to its Control.

Then this app needs to call `shell.setActive()`.

>> Ctrl+Shift+T
> Can you explain what did you change in your patch to solve that?

I've rewritten it. This problem does not occur any more according to my tests. Could you still reproduce it?

**Closed** 2023-07-02 18:49 UTC

**Comment by jukzi** [comment] 2023-07-11 18:08
I vote against such breaking change that causes regression in long standing applications. The right way would be to add additional API, fix existing javadoc  - and optionally deprecate existing API (removal=false) to give the user a hint.
see https://www.hyrumslaw.com/
it's not even obvious how that would behave on RAP now (https://github.com/eclipse-rap/org.eclipse.rap/blob/8779389119c29da298ee616f5989256752eb1e9f/bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/widgets/Control.java#L866).

**Comment by SyntevoAlex** [comment] 2023-07-11 18:19
I don't expect too many problems.

> The right way would be to add additional API

"The right way" depends on circumstances. Imagine if every single bug was only fixed by creating a new API? What a mess that would be! And lots of copy&paste code to support for years.

So it's really a question of how many regressions there would be, and how hard are they. So far there is one low-damage regression https://github.com/eclipse-platform/eclipse.platform.ui/issues/929 which occurs when user does something that is more like an error than a useful behavior.

Too early to make conclusions.

**Comment by mickaelistria** [comment] 2023-07-12 07:26
While this change is correct for the use-case mentioned in the report and from literal interpretation of the Javadoc contract, this change is very disruptive and many consumers of `setFocus` who were happy to get the shell brought to front by the way will be unhappy with it and feel it as regression. I'm afraid there are many of those all over existing plugins and we cannot fairly change the behavior if it requires many consumers to adapt their code to get the expected behavior; as in practice, very few will do and the overall quality of existing plugins will diminish and users will just find Eclipse is less stable.
We already had a few noticed regressions inside Platform for this -and Platform is supposed to be highest quality Eclipse-based code-, so we can just imagine that widening to the whole ecosystem, impacts of this change that are interpreted as regressions can be hundreds.
I am in favor of reverting and I think the suggestion from @jukzi to add a new API method (`setFocus(boolean bringToFront)` makes more sense than changing the behavior of `setFocus`.

**Comment by tmssngr** [comment] 2023-07-12 08:42
Why not let the users report regressions and developers (e.g. of plugins) fix their own code? For those users who have reported the bug, they can use the system property workaround until the source of the problem is fixed.
Do you prefer a buggy API with side effects where some users expect those side effects, or a clean one that does what the name/documentation states?

**Comment by mickaelistria** [comment] 2023-07-12 09:11
> Why not let the users report regressions and developers (e.g. of plugins) fix their own code? 

Because many plugins receive very low maintenance, the stability of the API and behavior of the Platform is one reason many plugins can still work with low maintenance. Minimizing the maintenance effort for downstream consumers has been for long one of the main key factor of success for Eclipse Platform.
Asking downstream community to change things because the API was not properly designed in 1st place isn't fair..

> Do you prefer a buggy API with side effects

Eclipse Platform prefer to not introuce regressions to downstream consumers when this can be avoided.
The side-effect has been there for too long and is too important; it's now part of the API and many people have used it relying on the side-effect (and not calling bringToFront). The method documentation should be changed to explicit this side-effect.

> a clean one that does what the name/documentation states?

Eclipse Platform is a 22 years-old project. There are some mistakes we cannot just easily undo because we have a community of consumers to serve well, we sometimes have to cope with those mistakes at best even if it's not the cleanest.

> Or would you also (as a bad example) mix setCaret with setFocus for text controls? 

I wouldn't. But if it were so for a long time that many people had relied on it, I would claim the same thing: stability and downstream consumers community matters more than dogmatic API management.

**Comment by jukzi** [comment] 2023-07-12 09:13
Our company alone would have to workaround in hundreds of repositories ...

**Comment by merks** [comment] 2023-07-12 09:21
I share the concerns expressed by @mickaelistria and @jukzi  because most likely downstream regression problems will not be noticed until after the release and then they will be noticed most likely by end users who will perceive this as poor Eclipse quality.

**Comment by tmssngr** [comment] 2023-07-12 09:25
Instead of reverting the whole patch, why not simply change the default in `Display.isActivateShellOnForceFocus`?

**Comment by mickaelistria** [comment] 2023-07-12 09:28
> Instead of reverting the whole patch, why not simply change the default in Display.isActivateShellOnForceFocus?

That would work. When I mean revert, I meant more reverting the behavior change than the code itself. so this proposal seems indeed good and better then reverting.

**Comment by tmssngr** [comment] 2023-07-12 10:24
I'm quite reluctant to add a new API just because it would be nice. We have already invested more than enough time and money in this fix (our company pays @SyntevoAlex for working on SWT). Hence, I'm only willing to spend the minimum effort to keep the fix in official SWT code. As we are maintaining a fork of SWT, in the worst case, only our fork would contain the fix - but I wanted to avoid that and improve the official SWT, so other users would not face the same problems or had to use our fork.

**Comment by tmssngr** [comment] 2023-07-12 13:47
> that's ok, but you should additionally add new API and use it where needed instead of using the property.

I have created following commit for discussion: https://github.com/syntevo/eclipse.platform.swt/commit/26edd96e5857a0507ae5aabbedb6f153472353ca (incomplete, because I've only changed it for Win32).

**Comment by tmssngr** [comment] 2023-07-13 10:47
Pull-request for a quickfix (changing the default): https://github.com/eclipse-platform/eclipse.platform.swt/pull/743

**Comment by tmssngr** [comment] 2023-07-13 12:43
Thanks, @jukzi, for your comments. I think I have addressed most of them in the latest above commit (not yet sent a pull-request for the API changes).

**Comment by tmssngr** [comment] 2023-07-18 14:19
OK, there is now new API `setFocus(boolean)` and `forceFocus(boolean)`. Existing code, even in SWT, continues using `setFocus()` and `forceFocus()` and the challenging part would now be to use the new API. For some invocations, e.g. in `CTabFolder.onKeyDown` or `StyledText.handleMouseDown` I reckon it would be safe to use `false` as `activateShell` parameter. But what to use in `Control.setTabItemFocus()` or `Control.fixFocus()`? I would avoid adding a new `activateShell` parameter to all those methods to tunnel this information through. Maybe the new API idea does not work good in this situation?

**Comment by jukzi** [comment] 2023-07-18 14:44
maybe just "never touch a running system" and only use new api where the old did not work

**Comment by ingomohr** [comment] 2023-07-22 11:13
### Is changing the behavior of old and existing API really a good idea?
I was just pointed to this issue by the [N&N for 4.29M1](https://eclipse.dev/eclipse/news/4.29/platform_isv.php). As far as I understand from that comment in the N&N the behavior of the existing API has changed w/ this issue - and that the behavior w/ the shell popping up had been there for quite a while.

Is it really a good idea to change the behavior of existing API when the old behavior was no recent bug?
Imho, this can cause regression problems with any SWT-based UI and, thus, increase the costs to migrate to a newer Eclipse version.

We imho really shouldn't want that. Not for SWT and not for any other API. API may have problems in what it documents vs what it does. But modifying it years later instead of just adding new API to fix the problems - in my opinion - drives client applications away from using those APIs, at all.

**Comment by tmssngr** [comment] 2023-07-24 07:14
@ingomohr According to my knowledge @mickaelistria was so kind to merge my pull request as commit bc9c59cc to change the default to the legacy (old) behavior. So code which relies on this incorrect old behavior will not break.

**Comment by mickaelistria** [comment] 2023-07-24 09:08
@ingomohr I think the code is fine now; however, the N&N must probably be modified to mention that the default behavior hasn't changed, but that the "feature flag" can be set to enable it.

**Comment by ingomohr** [comment] 2023-07-24 09:29
Thanks for the update, @mickaelistria !

**Comment by merks** [comment] 2023-08-30 07:40
The new and noteworthy is wrong at right now:

![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/208716/784471c6-c585-4a6d-976e-7b832b0d1706)

I believe the flag org.eclipse.swt.internal.activateShellOnForceFocus effectively defaults to false:

![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/208716/6e9a1f2a-25c9-4839-9b94-3af69e4a3679)

So I will update the description accordingly.  OK?

**Comment by merks** [comment] 2023-08-30 08:05
Hmmm, I thought this was changed for this not to be the default, but I think I'm misreading the code.  Or?

**Comment by syntevo** [comment] 2023-08-30 08:09
Yes, the news and noteworthy is incorrect now as the default has been changed to the old (legacy) behavior.

**Comment by merks** [comment] 2023-08-30 08:10
Yes, I looked again and of course the "true" argument to getProperty determines the default.  I will reference this issue in the PR to update the N&N.
