### ISSUE TITLE
Text doesn't appear in documentation popup

### ISSUE THREAD

**Issue by moabson** [eclipse-platform/eclipse.platform.swt#1173] opened 2023-10-04 23:17 UTC
I'm trying to see the documentation using the F2 shortcut, but the text isn't visible in the popup

Version: 2023-09 (4.29.0)
Build id: 20230907-1323

![eclipse_doc_popup](https://github.com/eclipse-platform/eclipse.platform.ui/assets/2575708/f2dc2651-3ad1-4206-a015-f2123a9ee7e3)

**Comment by iloveeclipse** [comment] 2024-04-15 14:24
I guess this is another reincarnation of webkit not being able to render on modern OS/HW.
Please try with `WEBKIT_DISABLE_DMABUF_RENDERER=1` environment variable set.

Most likely duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/843

**Closed by iloveeclipse** 2024-04-15 14:24 UTC
